<?php 
use App\Library\FuncionesGlobales;
?>
<style>
    .list-group-item {
      border: none; /* Elimina los bordes */
      cursor: pointer; /* Cambia el cursor al pasar por el div padre */
    }

    .hide{
        display: none;
    }

    .div_label_accion {
        margin-bottom: 5px; /* Reduce el espacio vertical entre los elementos */
        padding: 0; /* Opcional: elimina el relleno interno si es necesario */
    }

    .visually-hidden-radio {
    position: absolute;
    opacity: 0;
    pointer-events: none;
    }

    .color-swatch-wrapper {
    display: inline-block;
    cursor: pointer;
    margin: 8px;
    }

    .color-swatch {
    display: inline-block;
    width: 32px;
    height: 32px;
    border-radius: 50%;
    border: 2px solid transparent;
    transition: border-color 0.2s ease-in-out, box-shadow 0.2s;
    position: relative;
    }

    .color-swatch .checkmark {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 16px;
    color: #333;
    opacity: 0;
    transition: opacity 0.2s ease-in-out;
    pointer-events: none;
    }

    input[type="radio"]:checked + .color-swatch .checkmark {
    opacity: 1;
    }

    input[type="radio"]:checked + .color-swatch {
    border-color: #555;
    box-shadow: 0 0 0 2px #fff, 0 0 0 4px #555;
    }



</style>

<div class="container mt-4">
    <!-- Section 1: Search Filters -->
    <div>
        <h2><?php echo FuncionesGlobales::UpperString($translations['html_services']); ?></h2>
    </div>
    <div id="header_filters" class="card mb-4">
        <div class="card-header">
            <h5><?php echo $translations['html_header_search']; ?></h5>
        </div>
        <div class="card-body">
            <form id="searchForm" class="row g-3">
                <div class="col-md-4">
                    <label for="nameFilter" class="form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave" placeholder="<?php echo $translations['html_title_access_key']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="nameFilter" class="form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" placeholder="<?php echo $translations['html_title_name']; ?>">
                </div>
                <div class="col-md-12 text-end">
                    <button type="button" class="btn btn-outline-dark" id="btnBuscar">
                        <i class="bi bi-search"></i> 
                        <?php echo $translations['html_btn_search']; ?>
                    </button>
                    <button type="button" class="btn btn-outline-dark" id="btnCrear">
                        <i class="bi bi-plus-lg"></i> 
                        <?php echo $translations['html_new']; ?>
                    </button>
                </div> 
            </form>
        </div>
    </div>

    <!-- Section 2: Data Table -->
    <div class="card">
        <div class="card-header">
            <h5><?php echo $translations['html_header_results']; ?></h5>
        </div>
        <div class="card-body">
            <table id="table_results" class="display table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th><?php echo $translations['html_access_key']; ?></th>
                        <th><?php echo $translations['html_name']; ?></th>
                        <th><?php echo $translations['html_price']; ?></th>
                        <th><?php echo $translations['html_duration']; ?></th>
                        <th><?php echo $translations['html_active']; ?></th>
                        <th><?php echo $translations['html_action']; ?></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_create" tabindex="-1" aria-labelledby="label_modal_create" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label_modal_create"><?php echo FuncionesGlobales::UpperString($translations['html_new']); ?></h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body col-md-12">
        <form id="form_modal_create" class="needs-validation" novalidate>
            <div class="row mb-3">
                <!-- Campo Clave -->
                <div class="col-md-6">
                    <label for="input_clave" class="col-form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_access_key']; ?></div>
                </div>
                <!-- Campo Nombre -->
                <div class="col-md-6">
                    <label for="input_nombre" class="col-form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_name']; ?></div>
                </div>
            </div>
            <div class="col-md-12">
                <label for="textarea_descripcion" class="col-form-label"><?php echo $translations['html_description']; ?></label>
                <textarea rows="2" class="form-control" id="textarea_descripcion"></textarea>
            </div>
            <div class="row mb-3">
                <!-- Campo Costo -->
                <div class="col-md-6">
                    <label for="input_price" class="col-form-label"><?php echo $translations['html_price']; ?></label>
                    <input type="number" class="form-control" id="input_price" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_access_key']; ?></div>
                </div>
                <!-- Campo Duracion -->
                <div class="col-md-6">
                    <label for="input_duration" class="col-form-label"><?php echo $translations['html_duration']; ?></label>
                    <input type="number" class="form-control" id="input_duration" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_duration']; ?></div>
                </div>
            </div>
                <div class="mt-3">
                <label class="form-label"><?php echo $translations['html_select_color']; ?></label>
                <div class="d-flex flex-wrap gap-2">
                    <?php
                    $colores = [
                        '#FFB6C1', // Rosa Pastel
                        '#AEC6CF', // Azul Pastel
                        '#C1E1C1', // Verde Pastel
                        '#E6E6FA', // Lavanda
                        '#B2F2BB', // Menta
                        '#FFDAB9', // Melocotón
                        '#D8BFD8', // Lila
                        '#FFFACD', // Amarillo Suave
                        '#FFB3BA', // Coral Pastel
                        '#AFEEEE'  // Celeste
                    ];
                    foreach ($colores as $index => $color) {
                        echo "
                        <label class='color-swatch-wrapper position-relative' title='$color'>
                            <input class='visually-hidden-radio' type='radio' name='color_pastel' value='$color'>
                            <span class='color-swatch' style='background-color: $color;'>
                                <span class='checkmark'>&#10003;</span>
                            </span>
                        </label>";
                    }
                    ?>
                </div>
            </div>

            
            <div id="alert_error_permisos" class="alert alert-danger align-items-center" role="alert" style="display:none;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div id="msg_error">
                    
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal"><?php echo $translations['html_btn_cancel']; ?></button>
        <button type="button" id="btnSave" class="btn btn-primary"><?php echo $translations['html_btn_save']; ?></button>
      </div>
    </div>
  </div>
</div>
<script>
    let module_servicios    = (function(){
        let draw            = 0;
        //  URL
        const controller    = '/Servicios';
        const url_index     = controller+"/index";
        const url_create    = controller+"/create";
        const url_delete    = controller+"/delete";
        const url_update    = controller+"/update";

        //  PERMISOS
        const action_create = '<?php echo $create; ?>';
        const action_update = '<?php echo $update; ?>';
        const action_delete = '<?php echo $delete; ?>';

        //  language
        const translations  = {
            emptyTable: "<?= $translations['table_no_data'] ?>",
            info: "<?= $translations['showing_info'] ?>",
            infoEmpty: "<?= $translations['no_records'] ?>",
            search: "<?= $translations['search'] ?>",
            paginate: {
                first: "<?= $translations['paginate_first'] ?>",
                last: "<?= $translations['paginate_last'] ?>",
                next: "<?= $translations['paginate_next'] ?>",
                previous: "<?= $translations['paginate_previous'] ?>"
            },
            title_update    : "<?= $translations['html_edit_record'] ?>",
            title_delete    : "<?= $translations['html_delete_record'] ?>",
            title_change    : "<?= $translations['html_active_deactivate'] ?>",
            confirm_delete  : "<?= $translations['html_confirm_delete']?>",
            confirm_update  : "<?= $translations['html_confirm_update']?>"
        };

        //  LISTA DE ERRORES EN MODAL
        const error_list = {
            price                   : "<?php echo $translations['html_error_price']; ?>",
            error_selected_color    : "<?php echo $translations['html_error_selected_color']; ?>",
        }

        // Variable global para almacenar la instancia de DataTable
        let table;

        // Función para inicializar o recargar la tabla
        // Función para inicializar o recargar la tabla
        function cargarTabla() {
            
            draw    ++;
            if (!table) {
                table = new DataTable('#table_results', {
                    dom: 'lrtip',
                    paging: true,
                    info: true,
                    lengthChange: false,
                    language: translations,
                    ordering: false,
                    serverSide: true,
                    ajax: {
                        url: url_index,
                        method: 'POST',
                        data: function (d) {
                            d.pageSize  = d.length == null || d.length == '' ? 1 : d.length;
                            d.offset    = d.start == null || d.start == '' ? 0 : d.start;
                            d.draw      = draw;
                            d.accion    = 'get_rows';
                            d.clave     = $("#input_clave").val();
                            d.nombre    = $("#input_nombre").val();
                        }
                    },
                    columns: [
                        { data: 'clave' }, // Columna 1
                        { data: 'nombre' }, // Columna 1
                        { data: 'costo' }, // Columna 1
                        { data: 'duracion_minutos' }, // Columna 1
                        { data: 'label_activo' }, // Columna 1
                        {
                            data: null, 
                            className: "text-center", // Centra el contenido de la celda
                            orderable: false, // Desactiva el ordenamiento para esta columna
                            render: function (data, type, row) {
                                draw    ++;
                                // `data` contiene el objeto completo de la fila
                                // Generamos un botón con un atributo dinámico para identificar la fila
                                let btn_update  = action_update ? 
                                '<button class="btn btn-outline-dark btn-sm btn_edit" data-id="'+data['id']+'" title="'+translations['title_update'] +'">' +
                                    '<i class="bi bi-pencil-fill"></i>'+
                                '</button>' +
                                '<button class="btn btn-outline-dark btn-sm btn_change_status" data-id="'+data['id']+'" data-estatus="'+data['estatus']+'" title="'+translations['title_change'] +'">' +
                                    '<i class="bi bi-arrow-repeat"></i>'+
                                '</button>'
                                
                                : '';

                                let btn_delete  = action_delete ? 
                                '<button class="btn btn-outline-dark btn-sm btn_delete" data-id="'+data['id']+'" data-clave="'+data['clave']+'" data-nombre="'+data['nombre']+'" title="'+translations['title_delete'] +'">' +
                                    '<i class="bi bi-trash3-fill"></i>'+
                                '</button>' : '';
                                return btn_update + btn_delete;
                            }
                        }
                    ],
                    createdRow: function (row, data, dataIndex) {
                        // Guardar el objeto completo en la fila como data
                        $(row).data('rowData', data);

                        if (data.codigo_color != null && data.codigo_color != '') {
                            $(row).find('td:eq(0)').css('background-color', data.codigo_color); // La sexta columna tiene índice 5
                            $(row).find('td:eq(1)').css('background-color', data.codigo_color); // La sexta columna tiene índice 5
                        }
                    }
                });
            } else {
                draw    ++;
                table.ajax.reload();
            }
        }

        $(document).ready(function(){
            cargarTabla();

            // Evento click del botón "Buscar"
            $("#header_filters").on('click',"#btnBuscar",function() {
                cargarTabla();
            });

            $("#header_filters").on('click',"#btnCrear",function() {
                showModal();
            });

            //  EVENTO BOTON EDITAR
            $("#table_results").on('click','.btn_change_status',async function(){
                let data        = $(this).closest('tr').data('rowData');
                const id        = data['id'];
                const estatus   = data['activo'];
                let btn     = $(this);
                
                let msg = translations['confirm_update'];
                const respuesta = await window.modalConfirm(msg);

                $(btn).prop('disabled',true);

                if (respuesta) {
                    $.ajax({
                        url     : url_update,
                        method  : 'POST',
                        data    :  {
                            accion  : 'change_status',
                            status_actual   : estatus,
                            nuevo_status    : estatus == 1 ? 0 : 1,
                            servicio        : data['clave'] + ' - ' +data['nombre'],
                            id      : id
                        },
                        success : function(data){
                            console.log('data');
                            console.log(data);
                            $(btn).prop('disabled',false);
                            showAlert('success',"Edici&oacute;n exitosa!");
                            cargarTabla();
                        },
                        error   : function(error){
                            actionJsonError(error,btn);
                        }
                    });
                } else {
                    $(btn).prop('disabled',false);
                }
            });

            $("#table_results").on('click','.btn_delete',async function() {

                let data = $(this).closest('tr').data('rowData');

                const id        = data['id'];
                const clave     = data['clave'];
                const nombre    = data['nombre'];
                const respuesta = await window.modalConfirm(translations['confirm_delete']);
                let btn         = $(this);

                $(btn).prop('disabled',true);

                if (respuesta) {
                    $.ajax({
                        url     : url_delete,
                        method  : 'POST',
                        data    : {
                            id      : id,
                            data_bitacora   : data

                        },
                        success : function(data){
                            console.log('data');
                            console.log(data);
                            $(btn).prop('disabled',false);
                            showAlert('success',"Borrado exitoso!");
                            cargarTabla();
                        },
                        error   : function(error){
                            actionJsonError(error,btn);
                        }
                    });
                } else {
                    $(btn).prop('disabled',false);
                }
            });

            //  EVENTO BOTON EDITAR
            $("#table_results").on('click','.btn_edit',function(){
                const id    = $(this).data('id');
                let btn     = $(this);
                $(btn).prop('disabled',true);
                $.ajax({
                    url     : url_index,
                    method  : 'POST',
                    data    :  {
                        accion  : 'get_info_edit',
                        id      : id
                    },
                    success : function(data){
                        console.log('data');
                        console.log(data);
                        $(btn).prop('disabled',false);
                        showModal(data[0]);
                    },
                    error   : function(error){
                        actionJsonError(error,btn);
                    }
                });
            });
        });

        function showModal(data = null){
            let modal_clone = $("#modal_create").clone().show();

            //  SU DATA TIENE VALOR, ESTA SE PINTA
            if (data != null){
                $(modal_clone).find('#input_clave').val(data['clave']);
                $(modal_clone).find('#input_nombre').val(data['nombre']);
                $(modal_clone).find('#textarea_descripcion').val(data['descripcion']);
                $(modal_clone).find('#input_price').val(data['costo']);
                $(modal_clone).find('#input_duration').val(data['duracion_minutos']);

                //  SE SELECCIONA EL COLOR QUE YA VIENE
                $(modal_clone).find('[name="color_pastel"]').each(function(){
                    if ($(this).val() == data['codigo_color']){
                        $(this).trigger('click');
                    }
                })
            }
            

            $(modal_clone).on('click','#btnSave',function(){
                let btn =  $(this);
                $(btn).prop('disable',true);

                const form = $(modal_clone).find('#form_modal_create')[0]; // Obtén el elemento DOM
                let flag_error  = false;
                if (form.checkValidity() === false) {
                    $(form).addClass('was-validated');
                    flag_error  = true;
                } else {
                    $(form).removeClass('was-validated');
                }

                //  VALIDA QUE LIGIERA UN COLOR
                if ($(modal_clone).find('[name="color_pastel"]:checked').length == 0){
                    $(modal_clone).find('#alert_error_permisos').find('#msg_error').html(error_list['error_selected_color']);
                    $(modal_clone).find('#alert_error_permisos').addClass('d-flex').show();
                    return false;
                } else {
                    $(modal_clone).find('#alert_error_permisos').removeClass('d-flex').hide();
                }
                //  VALIDAR REGISTROS
                if ($(modal_clone).find("#input_price").val() != '' && !validarCantidadMonetaria($(modal_clone).find("#input_price").val())){
                    $(modal_clone).find('#alert_error_permisos').find('#msg_error').html(error_list['price']);
                    $(modal_clone).find('#alert_error_permisos').addClass('d-flex').show();
                    return false;
                } else {
                    $(modal_clone).find('#alert_error_permisos').removeClass('d-flex').hide();
                }

                if(flag_error){
                    return false;
                }

                let obj_info    = {
                    clave   : $(modal_clone).find('#input_clave').val(),
                    nombre  : $(modal_clone).find('#input_nombre').val(),
                    descripcion : $(modal_clone).find('#textarea_descripcion').val(),
                    costo       : $(modal_clone).find('#input_price').val(),
                    duracion    : $(modal_clone).find('#input_duration').val(),
                    codigo_color    : $(modal_clone).find('[name="color_pastel"]:checked').val() 
                };

                if (data != null){
                    obj_info['id']              = data['id'];
                    obj_info['clave_old']       = data['clave'];
                    obj_info['nombre_old']      = data['nombre'];
                    obj_info['costo_old']       = data['costo'];
                    obj_info['duracion_old']    = data['duracion_minutos'];
                    obj_info['color_old']       = data['codigo_color'];
                }

                console.log('obj_info');
                console.log(obj_info);
                //return false;

                //  AJAX SAVE
                $.ajax({
                    url         : data == null ? url_create : url_update,
                    method      : 'POST',
                    dataType    : 'json',
                    data        : obj_info,
                    success     : function(data){
                        $(btn).prop('disabled',false);
                        $(modal_clone).modal('hide');
                        showAlert('success',data);
                        cargarTabla();
                    },
                    error     : function(error){
                        actionJsonError(error,btn);
                    }
                })
            });

            $(modal_clone).modal('show');
        }
    })();
</script>