<?php 
use App\Library\FuncionesGlobales;
?>
<style>
    .list-group-item {
      border: none; /* Elimina los bordes */
      cursor: pointer; /* Cambia el cursor al pasar por el div padre */
    }

    .hide{
        display: none;
    }

    .div_label_accion {
        margin-bottom: 5px; /* Reduce el espacio vertical entre los elementos */
        padding: 0; /* Opcional: elimina el relleno interno si es necesario */
    }

</style>
<div class="container mt-4">
    <!-- Section 1: Search Filters -->
    <div id="header_filters" class="card mb-4">
        <div class="card-header">
            <h5><?php echo $translations['html_header_search']; ?></h5>
        </div>
        <div class="card-body">
            <form id="searchForm" class="row g-3">
                <div class="col-md-4">
                    <label for="input_clave" class="form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave" placeholder="<?php echo $translations['html_title_access_key']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="input_primer_apellido" class="form-label"><?php echo $translations['html_first_lastname']; ?></label>
                    <input type="text" class="form-control" id="input_primer_apellido" placeholder="<?php echo $translations['html_title_lastname']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="input_segundo_apellido" class="form-label"><?php echo $translations['html_second_lastname']; ?></label>
                    <input type="text" class="form-control" id="input_segundo_apellido" placeholder="<?php echo $translations['html_title_lastname']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="input_nombre" class="form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" placeholder="<?php echo $translations['html_title_name']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="select_servicios" class="form-label"><?php echo $translations['html_services']; ?></label>
                    <select id="select_servicios" class="form-select" aria-label="Default select example">
                        <option></option>
                        <?php foreach($arr_servicios as $servicio): ?>
                            <option value="<?php echo $servicio['id']; ?>"><?php echo $servicio['nombre']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="select_locaciones" class="form-label"><?php echo $translations['html_locations']; ?></label>
                    <select id="select_locaciones" class="form-select" aria-label="Default select example">
                        <option></option>
                        <?php foreach($arr_locaciones as $locacion): ?>
                            <option value="<?php echo $locacion['id']; ?>"><?php echo $locacion['nombre']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-12 text-end">
                    <button type="button" class="btn btn-outline-dark" id="btnBuscar">
                        <i class="bi bi-search"></i> 
                        <?php echo $translations['html_btn_search']; ?>
                    </button>
                    <button type="button" class="btn btn-outline-dark" id="btnCrear">
                        <i class="bi bi-plus-lg"></i> 
                        <?php echo $translations['html_new']; ?>
                    </button>
                    <button type="button" class="btn btn-outline-dark" id="btnCrearExpress">
                        <i class="bi bi-plus-lg"></i> 
                        <?php echo $translations['html_express_new_record']; ?>
                    </button>
                </div> 
            </form>
        </div>
    </div>

    <!-- Section 2: Data Table -->
    <div class="card">
        <div class="card-header">
            <h5><?php echo $translations['html_header_results']; ?></h5>
        </div>
        <div class="card-body">
            <table id="table_results" class="display table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th><?php echo $translations['html_access_key']; ?></th>
                        <th><?php echo $translations['html_name']; ?></th>
                        <th><?php echo $translations['html_cellphone']; ?></th>
                        <th><?php echo $translations['html_assigned_services']; ?></th>
                        <th><?php echo $translations['html_location']; ?></th>
                        <th><?php echo $translations['html_status']; ?></th>
                        <th><?php echo $translations['html_action']; ?></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_create" tabindex="-1" aria-labelledby="label_modal_create" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label_modal_create"><?php echo FuncionesGlobales::UpperString($translations['html_new']); ?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body col-md-12">
        <form id="form_modal_create" class="needs-validation" novalidate>
            <div class="row mb-3">
                <div class="col-md-6">
                    <label for="select_locaciones" class="form-label"><?php echo $translations['html_locations']; ?></label>
                    <select id="select_locaciones" class="form-select" aria-label="Default select example" <?php echo count($arr_locaciones) == 1 ? 'disabled' : ''; ?> required>
                        <option></option>
                        <?php foreach($arr_locaciones as $locacion): ?>
                            <option value="<?php echo $locacion['id']; ?>" <?php echo count($arr_locaciones) == 1 ? 'selected' : ''; ?>><?php echo $locacion['nombre']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <div class="invalid-feedback"><?php echo $translations['html_error_selected_location']; ?></div>
                </div>                
                <!-- Campo Clave -->
                <div class="col-md-6">
                    <label for="input_celular" class="col-form-label"><?php echo $translations['html_cellphone']; ?></label>
                    <input type="text" id="input_celular" name="input_celular" class="form-control" maxLength="10" required />
                    <div class="invalid-feedback"><?php echo $translations['html_error_cellphone']; ?></div>
                </div>
                <!-- Campo Nombre -->
                <div class="col-md-6">
                    <label for="input_primer_apellido" class="col-form-label"><?php echo $translations['html_first_lastname']; ?></label>
                    <input type="text" class="form-control" id="input_primer_apellido" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_first_lastname']; ?></div>
                </div>
                <div class="col-md-6">
                    <label for="input_segundo_apellido" class="col-form-label"><?php echo $translations['html_second_lastname']; ?></label>
                    <input type="text" class="form-control" id="input_segundo_apellido">
                </div>
                <!-- Campo Nombre -->
                <div class="col-md-6">
                    <label for="input_nombre" class="col-form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_name']; ?></div>
                </div>
            
            <div id="alert_error_permisos" class="alert alert-danger align-items-center" role="alert" style="display:none;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div id="msg_error">
                    
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal"><?php echo $translations['html_btn_cancel']; ?></button>
        <button type="button" id="btnSave" class="btn btn-primary"><?php echo $translations['html_btn_save']; ?></button>
      </div>
    </div>
  </div>
</div>

<script>
    let modulo_patients = (function(){
        let draw            = 1;
        //  URL
        const controller    = '/Pacientes';
        const url_index     = controller+"/index";
        const url_create    = controller+"/create";
        const url_delete    = controller+"/delete";
        const url_update    = controller+"/update";
        const url_preview   = controller+"/preview";

        //  PERMISOS
        const action_create = '<?php echo $create; ?>';
        const action_update = '<?php echo $update; ?>';
        const action_detele = '<?php echo $delete; ?>';

        //  language
        const translations  = {
            emptyTable: "<?= $translations['table_no_data'] ?>",
            info: "<?= $translations['showing_info'] ?>",
            infoEmpty: "<?= $translations['no_records'] ?>",
            search: "<?= $translations['search'] ?>",
            paginate: {
                first: "<?= $translations['paginate_first'] ?>",
                last: "<?= $translations['paginate_last'] ?>",
                next: "<?= $translations['paginate_next'] ?>",
                previous: "<?= $translations['paginate_previous'] ?>"
            },
            title_update    : "<?= $translations['html_edit_record'] ?>",
            title_delete    : "<?= $translations['html_delete_record'] ?>",
            title_preview   : "<?= $translations['html_preview_record'] ?>",
            title_change    : "<?= $translations['html_active_deactivate'] ?>",
            confirm_delete  : "<?= $translations['html_confirm_delete']?>"
        };

        //  LISTA DE ERRORES EN MODAL
        const error_list = {
            sin_permisos    : "<?php echo $translations['html_error_empty_list']; ?>",
            error_email     : "<?php echo $translations['html_error_email']; ?>",
            error_celular   : "<?php echo $translations['html_error_cellphone']; ?>",
            error_contrasena    : "<?php echo $translations['html_error_different_password']; ?>",
            error_length_contrasena : "<?php echo $translations['html_error_length_password']; ?>",
        }

        // Variable global para almacenar la instancia de DataTable
        let table;

        $(document).ready(function(){
            cargarTabla();

            selectToSelect2($("#header_filters"),"select_servicios");
            selectToSelect2($("#header_filters"),"select_locaciones");

            // Evento click del botón "Buscar"
            $("#header_filters").on('click',"#btnBuscar",function() {
                cargarTabla();
            });

            // Evento click del botón "CREACION EXPRESS"
            $("#header_filters").on('click',"#btnCrearExpress",function() {
                creacionExpress();
            });
        });

        // Función para inicializar o recargar la tabla
        function cargarTabla() {
            draw    ++;
            if (!table) {
                table = new DataTable('#table_results', {
                    dom: 'lrtip',
                    paging: true,
                    info: true,
                    lengthChange: false,
                    language: translations,
                    serverSide: true,
                    ajax: {
                        url: url_index,
                        method: 'POST',
                        data: function (d) {
                            d.pageSize  = d.length == null || d.length == '' ? 1 : d.length;
                            d.offset    = d.start == null || d.start == '' ? 0 : d.start;
                            d.draw      = draw;
                            d.accion    = 'get_rows';
                            d.clave     = $("#input_clave").val();
                            d.primer_apellido   = $("#input_primer_apellido").val();
                            d.segundo_apellido  = $("#input_segundo_apellido").val();
                            d.nombre            = $("#input_nombre").val();
                            d.id_servicio       = $("#select_servicios").val();
                            d.id_locacion_registro  = $("#select_locaciones").val();
                        },
                        dataSrc: function (json) {
                            console.log("DataTables Response:", json); // <---- Depuración
                            return json.data;
                        }
                    },
                    columns: [
                        { data: 'clave' }, // Columna 1
                        { data: 'nombre_completo' }, // Columna 1
                        { data: 'celular' }, // Columna 1
                        { data: 'num_servicios' }, // Columna 1
                        { data: 'locacion_registro' }, // Columna 1
                        { data: 'label_estatus' }, // Columna 1
                        {
                            data: null, 
                            className: "text-center", // Centra el contenido de la celda
                            orderable: false, // Desactiva el ordenamiento para esta columna
                            render: function (data, type, row) {
                                draw    ++;
                                // `data` contiene el objeto completo de la fila
                                // Generamos un botón con un atributo dinámico para identificar la fila
                                let btn_preview = url_preview ?
                                '<button class="btn btn-outline-dark btn-sm btn_preview" data-id="'+data['id']+'" title="'+translations['title_preview'] +'">' +
                                    '<i class="bi bi-search"></i> '+
                                '</button>' : '';
                                
                                let btn_update  = action_update ? 
                                '<button class="btn btn-outline-dark btn-sm btn_edit" data-id="'+data['id']+'" title="'+translations['title_update'] +'">' +
                                    '<i class="bi bi-pencil-fill"></i>'+
                                '</button>' +
                                '<button class="btn btn-outline-dark btn-sm btn_change_status" data-id="'+data['id']+'" data-estatus="'+data['estatus']+'" title="'+translations['title_change'] +'">' +
                                    '<i class="bi bi-arrow-repeat"></i>'+
                                '</button>'
                                
                                : '';

                                let btn_delete  = action_update ? 
                                '<button class="btn btn-outline-dark btn-sm btn_delete" data-id="'+data['id']+'" data-clave="'+data['clave']+'" data-activo="'+data['activo']+'" title="'+translations['title_delete'] +'">' +
                                    '<i class="bi bi-trash3-fill"></i>'+
                                '</button>' : '';
                                return btn_preview + btn_update + btn_delete;
                            }
                        }
                    ]
                });
            } else {
                draw    ++;
                table.ajax.reload();
            }
        }

        function creacionExpress(){
            let modal_clone = $("#modal_create").clone().show();

            $(modal_clone).find('#select_locaciones').select2({
                placeholder     : 'Seleccione una opción',
                dropdownParent: $(modal_clone)
            });

            //  EVENTOS
            $(modal_clone).on('keypress','#input_celular',function(e) {
                if(isNaN(this.value + String.fromCharCode(e.charCode))) 
                return false;
            })
            .on("cut copy paste",function(e){
                e.preventDefault();
            });

            $(modal_clone).on('click','#btnSave',function(){
                let btn =  $(this);
                $(btn).prop('disable',true);

                const form = $(modal_clone).find('#form_modal_create')[0]; // Obtén el elemento DOM
                let flag_error  = false;
                if (form.checkValidity() === false) {
                    $(form).addClass('was-validated');
                    flag_error  = true;
                } else {
                    $(form).removeClass('was-validated');
                }

                //  VALIDAR ESTRUCTURA DE DATOS
                if (parseInt($(modal_clone).find('#input_celular').val().length) != parseInt(10)){
                    console.log('pase1');
                    $(modal_clone).find('#alert_error_permisos').find('#msg_error').html(error_list['error_celular']);
                    $(modal_clone).find('#alert_error_permisos').addClass('d-flex').show();
                    return false;
                } else {
                    $(modal_clone).find('#alert_error_permisos').removeClass('d-flex').hide();
                }

                if (flag_error){
                    return false;
                }

                let obj_info    = {
                    celular             : $(modal_clone).find('#input_celular').val(),
                    primer_apellido     : $(modal_clone).find('#input_primer_apellido').val(),
                    segundo_apellido    : $(modal_clone).find('#input_segundo_apellido').val(),
                    nombre              : $(modal_clone).find('#input_nombre').val(),
                    id_locacion_registro    : $(modal_clone).find('#select_locaciones').val(),
                    label_locacion          : $(modal_clone).find('#select_locaciones').find('option:selected').text(),
                };

                console.log('obj_info');
                console.log(obj_info);
                //return false;

                //  AJAX SAVE
                $.ajax({
                    url         : url_create,
                    method      : 'POST',
                    dataType    : 'json',
                    data        : {
                        obj_info    : obj_info,
                        accion      : 'create_express'
                    },
                    success     : function(data){
                        $(btn).prop('disabled',false);
                        $(modal_clone).modal('hide');
                        showAlert('success',data);
                        cargarTabla();
                    },
                    error     : function(error){
                        actionJsonError(error,btn);
                    }
                })
            });

            $(modal_clone).modal('show');
        }
    })();  
</script>