<?php 
use App\Library\FuncionesGlobales;
?>
<style>
    .list-group-item {
      border: none; /* Elimina los bordes */
      cursor: pointer; /* Cambia el cursor al pasar por el div padre */
    }

    .hide{
        display: none;
    }

    .div_label_accion {
        margin-bottom: 5px; /* Reduce el espacio vertical entre los elementos */
        padding: 0; /* Opcional: elimina el relleno interno si es necesario */
    }

    .is-invalid {
        border: 1px solid #dc3545 !important; /* Color rojo típico para errores */
        border-radius: 4px; /* Bordes redondeados, si es que los usa validateForm */
        box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25); /* Sombra para resaltar el campo */
    }

    .div_append_service {
        height: 320px;
        overflow: scroll;
    }

    .form-check-input {
        transform: scale(1.5); /* Aumenta el tamaño del switch */
        width: 5rem; /* Ajusta el ancho del switch */
    }

</style>
<div class="container mt-4">
    <!-- Section 1: Search Filters -->
    <div>
        <h2><?php echo FuncionesGlobales::UpperString($translations['html_title_patients']); ?></h2>
    </div>
    <div id="header_filters" class="card mb-4">
        <div class="card-header">
            <h5><?php echo $translations['html_header_search']; ?></h5>
        </div>
        <div class="card-body">
            <form id="searchForm" class="row g-3">
                <div class="col-md-4">
                    <label for="input_clave" class="form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave" placeholder="<?php echo $translations['html_title_access_key']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="input_primer_apellido" class="form-label"><?php echo $translations['html_first_lastname']; ?></label>
                    <input type="text" class="form-control" id="input_primer_apellido" placeholder="<?php echo $translations['html_title_lastname']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="input_segundo_apellido" class="form-label"><?php echo $translations['html_second_lastname']; ?></label>
                    <input type="text" class="form-control" id="input_segundo_apellido" placeholder="<?php echo $translations['html_title_lastname']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="input_nombre" class="form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" placeholder="<?php echo $translations['html_title_name']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="select_servicios" class="form-label"><?php echo $translations['html_services']; ?></label>
                    <select id="select_servicios" class="form-select" aria-label="Default select example">
                        <option></option>
                        <?php foreach($arr_servicios as $servicio): ?>
                            <option value="<?php echo $servicio['id']; ?>"><?php echo $servicio['nombre']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="select_locaciones" class="form-label"><?php echo $translations['html_locations']; ?></label>
                    <select id="select_locaciones" class="form-select select_locaciones" aria-label="Default select example">
                        <option></option>
                        <?php foreach($arr_locaciones as $locacion): ?>
                            <option value="<?php echo $locacion['id']; ?>"><?php echo $locacion['nombre']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-12 text-end">
                    <button type="button" class="btn btn-outline-dark" id="btnBuscar">
                        <i class="bi bi-search"></i> 
                        <?php echo $translations['html_btn_search']; ?>
                    </button>
                    <?php if ($create): ?>
                    <button type="button" class="btn btn-outline-dark" id="btnCrearExpress">
                        <i class="bi bi-plus-lg"></i> 
                        <?php echo $translations['html_express_new_record']; ?>
                    </button>
                    <?php endif; ?>
                </div> 
            </form>
        </div>
    </div>

    <!-- Section 2: Data Table -->
    <div class="card">
        <div class="card-header">
            <h5><?php echo $translations['html_header_results']; ?></h5>
        </div>
        <div class="card-body">
            <table id="table_results" class="display table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th><?php echo $translations['html_access_key']; ?></th>
                        <th><?php echo $translations['html_name']; ?></th>
                        <th><?php echo $translations['html_cellphone']; ?></th>
                        <th><?php echo $translations['html_birthdate']; ?></th>
                        <th><?php echo $translations['html_current_age']; ?></th>
                        <th><?php echo $translations['html_assigned_services']; ?></th>
                        <th><?php echo $translations['html_registered_diagnoses']; ?></th>
                        <th><?php echo $translations['html_status']; ?></th>
                        <th><?php echo $translations['html_action']; ?></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<!-- d-flex -->
<div id="template_service" class="row align-items-center" style="display:none;">
    <div class="col-md-4 fix-padding">
        <label for="select_servicios" class="form-label"><?php echo $translations['html_services']; ?></label>
        <select class="form-select select_servicios" aria-label="Default select example" required>
            <option></option>
        </select>
        <div class="invalid-feedback"><?php echo $translations['html_error_service']; ?></div>
    </div>                
    <!-- Campo Clave -->
    <div class="col-md-4 fix-padding div_header_profesionales">
        <label for="select_profesionales" class="form-label"><?php echo $translations['html_title_professional']; ?></label>
        <select class="form-select select_profesionales" aria-label="Default select example" required>
            <option></option>
        </select>
        <div class="invalid-feedback"><?php echo $translations['html_error_professional']; ?></div>
    </div>
    <div class="col-md-2 fix-padding">
        <label for="btn_add_hours" class="form-label"><?php echo $translations['html_add_hours']; ?></label>
        <button type="button" class="btn btn-outline-dark btn_add_hours" title="<?php echo $translations['html_title_add_hour']; ?>"><i class="bi bi-plus"></i></button>
    </div>
    <div class="col-md-2 fix-padding">
        <label for="btn_delete_service" class="form-label"><?php echo $translations['html_delete_service']; ?></label>
        <button type="button" class="btn btn-outline-dark btn_delete_service" title="<?php echo $translations['html_title_delete_service']; ?>"><i class="bi bi-x"></i></button>
    </div>

    <!-- Campo Nombre -->
    <div class="row align-items-center div_append_hours" style="padding-left:30px;padding-right:10px;"></div>
</div>

<div id="template_hours" style="display:none;">
    <div class="col-md-3 fix-padding" style="padding-right:5px;">
        <label for="select_dias" class="form-label"><?php echo $translations['html_day']; ?></label>
        <select class="form-select select_dias" aria-label="Default select example" required>
            <option></option>
            <option value="1"><?php echo $translations['html_monday']; ?></option>
            <option value="2"><?php echo $translations['html_thuesday']; ?></option>
            <option value="3"><?php echo $translations['html_wednesday']; ?></option>
            <option value="4"><?php echo $translations['html_thursday']; ?></option>
            <option value="5"><?php echo $translations['html_friday']; ?></option>
            <option value="6"><?php echo $translations['html_saturday']; ?></option>
        </select>
        <div class="invalid-feedback"><?php echo $translations['html_error_day']; ?></div>
    </div>
    <div class="col-md-2" style="padding-right:5px;">
        <label for="input_hora_inicio" class="col-form-label"><?php echo $translations['html_starting_hour']; ?></label>
        <input type="time" step="60" class="form-control input_hora_inicio" disabled required>
        <div class="invalid-feedback"><?php echo $translations['html_error_starting_hour']; ?></div>
    </div>
    <div class="col-md-2 fix-padding" align="center">
        <label for="span_duracion" class="form-label" style="width:100%" title="<?php echo $translations['html_duration']; ?>"><?php echo $translations['html_ab_duration']; ?></label>
        <span class="span_duracion"></span>
    </div>
    <!-- Campo Nombre -->
    <div class="col-md-2" style="padding-right:5px;">
        <label for="input_hora_termino" class="col-form-label"><?php echo $translations['html_ending_hour']; ?></label>
        <input type="time" step="60" class="form-control input_hora_termino" required>
        <div class="invalid-feedback"><?php echo $translations['html_error_ending_hour']; ?></div>
    </div>
    <div class="col-md-2">
        <label for="btn_delete_hour" class="form-label" style="padding-top: 6px"><?php echo $translations['html_delete_hours']; ?></label><br>
        <button type="button" class="btn btn-outline-dark btn_delete_hour" title="<?php echo $translations['html_title_delete_hour']; ?>"><i class="bi bi-x"></i></button>
    </div>
</div>

<div class="modal fade" id="modal_create" tabindex="-1" aria-labelledby="label_modal_create" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label_modal_create"><?php echo FuncionesGlobales::UpperString($translations['html_new']); ?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body col-md-12">
        <form id="form_modal_create" class="needs-validation" novalidate>
            <div class="row mb-3">
                <div class="col-md-6 fix-padding">
                    <label for="select_locaciones" class="form-label"><?php echo $translations['html_locations']; ?></label>
                    <select id="select_locaciones" class="form-select" aria-label="Default select example" <?php echo count($arr_locaciones) == 1 ? 'disabled' : ''; ?> required>
                        <option></option>
                        <?php foreach($arr_locaciones as $locacion): ?>
                            <option value="<?php echo $locacion['id']; ?>" <?php echo count($arr_locaciones) == 1 ? 'selected' : ''; ?>><?php echo $locacion['nombre']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <div class="invalid-feedback"><?php echo $translations['html_error_selected_location']; ?></div>
                </div>                
                <!-- Campo Clave -->
                <div class="col-md-6">
                    <label for="input_celular" class="col-form-label"><?php echo $translations['html_cellphone']; ?></label>
                    <input type="text" id="input_celular" name="input_celular" class="form-control" maxLength="10" required />
                    <div class="invalid-feedback"><?php echo $translations['html_error_cellphone']; ?></div>
                </div>
                <!-- Campo Nombre -->
                <div class="col-md-6">
                    <label for="input_primer_apellido" class="col-form-label"><?php echo $translations['html_first_lastname']; ?></label>
                    <input type="text" class="form-control" id="input_primer_apellido" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_first_lastname']; ?></div>
                </div>
                <div class="col-md-6">
                    <label for="input_segundo_apellido" class="col-form-label"><?php echo $translations['html_second_lastname']; ?></label>
                    <input type="text" class="form-control" id="input_segundo_apellido">
                </div>
                <!-- Campo Nombre -->
                <div class="col-md-6">
                    <label for="input_nombre" class="col-form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_name']; ?></div>
                </div>
                <!-- Campo fecha nacimiento -->
                <div class="col-md-6">
                    <label for="input_fecha_nacimiento" class="col-form-label"><?php echo $translations['html_birthdate']; ?></label>
                    <input type="date" class="form-control" id="input_fecha_nacimiento">
                    <div class="invalid-feedback"><?php echo $translations['html_error_birthdate']; ?></div>
                </div>
            
            <div id="alert_error" class="alert alert-danger align-items-center" role="alert" style="display:none;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div id="msg_error">
                    
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal"><?php echo $translations['html_btn_cancel']; ?></button>
        <button type="button" id="btnSave" class="btn btn-primary"><?php echo $translations['html_btn_save']; ?></button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal_diagnostico" tabindex="-1" aria-labelledby="label_modal_diagnostico" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label_modal_diagnostico"><?php echo FuncionesGlobales::UpperString($translations['html_diagnosis_capture']); ?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body col-md-12">
        <form id="form_modal_create" class="needs-validation" novalidate>
            <div class="row mb-3">            
                <!-- Campo Clave -->
                <div class="col-md-12">
                    <label><?php echo $translations['html_title_patient']; ?>:</label>
                    <div id="nombre_paciente" class="d-block"></div>
                </div>
                <!-- Campo Nombre -->
                <div class="col-md-12">
                    <label for="input_diagnoses" class="col-form-label"><?php echo $translations['html_registered_diagnoses']; ?></label>
                </div>
                <div class="div_lista_diagnosticos col-md-12">
                    <div class="row">
                        <div class="col-md-2"><?php echo $translations['html_abrev']; ?></div>
                        <div class="col-md-8"><?php echo $translations['html_diagnoses']; ?></div>
                        <div class="col-md-2"><?php echo $translations['html_evidence']; ?></div>
                    </div>
                    
                    <?php foreach($arr_transtornos as $row): ?>
                        <div data-id="<?php echo $row['id']; ?>" class="row div_diagnostico" id="diagnostico_<?php echo $row['id']; ?>">
                            <div class="col-md-2"><?php echo ($row['clave']); ?></div>
                            <div class="col-md-8"><?php echo ($row['nombre']); ?></div>
                            <div class="col-md-2" align="center"><input type="checkbox" class="input_evidencia"  disabled/></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            
                <div id="alert_error" class="alert alert-danger align-items-center" role="alert" style="display:none;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </svg>
                <div id="msg_error">
                    
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal"><?php echo $translations['html_btn_cancel']; ?></button>
        <button type="button" id="btnSave" class="btn btn-primary"><?php echo $translations['html_btn_save']; ?></button>
      </div>
    </div>
  </div>
</div>

<script>
    let modulo_patients = (function(){
        let count_add_row_service   = 0;
        let count_hours             = 0;
        let draw            = 1;
        //  URL
        const controller    = '/Pacientes';
        const url_index     = controller+"/index";
        const url_create    = controller+"/create";
        const url_delete    = controller+"/delete";
        const url_update    = controller+"/update";
        const url_preview   = controller+"/preview";

        //  PERMISOS
        const action_create = '<?php echo $create; ?>';
        const action_update = '<?php echo $update; ?>';
        const action_delete = '<?php echo $delete; ?>';
        const action_schedule_appointments  = '<?php echo $schedule_appointments; ?>';

        //  language
        const translations  = {
            emptyTable: "<?= $translations['table_no_data'] ?>",
            info: "<?= $translations['showing_info'] ?>",
            infoEmpty: "<?= $translations['no_records'] ?>",
            search: "<?= $translations['search'] ?>",
            paginate: {
                first: "<?= $translations['paginate_first'] ?>",
                last: "<?= $translations['paginate_last'] ?>",
                next: "<?= $translations['paginate_next'] ?>",
                previous: "<?= $translations['paginate_previous'] ?>"
            },
            title_update    : "<?= $translations['html_edit_record'] ?>",
            title_delete    : "<?= $translations['html_delete_record'] ?>",
            title_preview   : "<?= $translations['html_preview_record'] ?>",
            title_change    : "<?= $translations['html_active_deactivate'] ?>",
            confirm_delete  : "<?= $translations['html_confirm_delete']?>",
            deactivate_patient      : "<?= $translations['html_deactivate_patient']?>",
            activate_patient        : "<?= $translations['html_activate_patient']?>",
            schedule_appointments   : "<?= $translations['html_schedule_appointments']?>",
            monday: "<?php echo $translations['html_monday'];     ?>",
            thuesday: "<?php echo $translations['html_thuesday'];   ?>",
            wednesday: "<?php echo $translations['html_wednesday'];  ?>",
            thursday: "<?php echo $translations['html_thursday'];   ?>",
            friday: "<?php echo $translations['html_friday'];     ?>",
            saturday: "<?php echo $translations['html_saturday'];   ?>",     
            diagnosis_capture  :  "<?php echo $translations['html_diagnosis_capture'];   ?>",
        };

        //  LISTA DE ERRORES EN MODAL
        const error_list = {
            sin_permisos    : "<?php echo $translations['html_error_empty_list']; ?>",
            error_email     : "<?php echo $translations['html_error_email']; ?>",
            error_celular   : "<?php echo $translations['html_error_cellphone']; ?>",
            error_contrasena    : "<?php echo $translations['html_error_different_password']; ?>",
            error_length_contrasena : "<?php echo $translations['html_error_length_password']; ?>",
            error_spliced           : "<?php echo $translations['html_error_spliced']; ?>",
            error_birthdate         : "<?php echo $translations['html_error_birthdate']; ?>"
        }

        // Variable global para almacenar la instancia de DataTable
        let table;

        $(document).ready(function(){
            cargarTabla();

            selectToSelect2($("#header_filters"),"select_servicios");
            selectToSelect2($("#header_filters"),"select_locaciones");

            // Evento click del botón "Buscar"
            $("#header_filters").on('click',"#btnBuscar",function() {
                cargarTabla();
            });

            // Evento click del botón "CREACION EXPRESS"
            $("#header_filters").on('click',"#btnCrearExpress",function() {
                show_modal_creacion();
            });

            //  EVENTO PARA PROGRAMAR UNA CITA
            //  EVENTO BOTON EDITAR
            $("#table_results").on('click','.btn_program_date',function(){

                let status  = $(this).closest('.text-center').find('.btn_change_status').data('estatus');

                if (status != 1){
                    showAlert('El paciente debe de estar activo para poder asignarle un horario de citas.');
                    return false;
                }

                const id             = $(this).data('id');
                window.location.href = '/Pacientes/scheduleappointments?id='+id;
                
            }); 

            //  EVENTO BOTON EDITAR
            $("#table_results").on('click','.btn_change_status',async function(){
                const id        = $(this).data('id');
                const estatus   = $(this).data('estatus');
                let btn     = $(this);
                $(btn).prop('disabled',true);
                
                let msg = estatus == 1 ? translations['deactivate_patient'] : translations['activate_patient'];
                const respuesta = await window.modalConfirm(msg);

                $(btn).prop('disabled',true);

                if (respuesta) {
                    $.ajax({
                        url     : url_update,
                        method  : 'POST',
                        data    :  {
                            accion  : 'change_status',
                            id      : id
                        },
                        success : function(data){
                            console.log('data');
                            console.log(data);
                            $(btn).prop('disabled',false);
                            showAlert('success',"Edici&oacute;n exitoso!");
                            cargarTabla();
                        },
                        error   : function(error){
                            actionJsonError(error,btn);
                        }
                    });
                } else {
                    $(btn).prop('disabled',false);
                }
            });

            $("#table_results").on('click','.btn_edit',function(){
                let data    = $(this).closest('tr').data('rowData');
                console.log('data',data);
                show_modal_creacion(data);
            });

            $("#table_results").on('click','.btn_diagnoses',function(){
                let data    = $(this).closest('tr').data('rowData');
                console.log('data',data);
                show_modal_diagnoses(data);
            });
        });

        //  FUNCION PARA LLENAR COMBO DE PROFESIONALES
        function fill_profesionales(header_template,id_locacion_registro,id_servicio,id_profesional = null){
            $.ajax({
                url     : url_index,
                method  : 'post',
                data    : {
                    accion      : 'get_profesionales',
                    id_locacion : id_locacion_registro,
                    id_servicio : id_servicio
                },
                success : function(data){
                    console.log('data');
                    console.log(data);

                    let option  = '<option></option>';
                    for(let i in data){
                        let selected    = id_profesional != null && id_profesional == data[i]['id'] ? 'selected' : '';
                        option  += '<option value="'+data[i]['id'] +'" '+selected+'>'+data[i]['nombre_completo']+'</option>';
                    }

                    $(header_template).find('.select_profesionales').find('option').remove();
                    $(header_template).find('.select_profesionales').append(option);
                    $(header_template).find('.input_hora_inicio').prop('disabled',false);
                },
                error   : function(error){
                    console.log('error');
                    console.log(error);
                }
            });
        }

        function add_template_service(modal_clone,all_services,id_locacion_registro,info_paciente = null){
            count_add_row_service   ++;
            count_hours             ++;
            let class_div_header    = 'div_'+count_add_row_service;
            let template_service    = $("#template_service").clone().removeAttr('id').addClass('header_service').addClass('d-flex').addClass(class_div_header).show();
            let template_hours      = $("#template_hours").clone().removeAttr('id').css('display','flex').addClass('row_hours').attr('id','row_'+count_hours);

            // Aplica select2 solo al nuevo select
            $(template_hours).find('.select_dias').select2({
                placeholder: 'Seleccione una opción',
                dropdownParent: $(modal_clone),
                width: '50px'
            });

            $(template_service).find('.select_profesionales').select2({
                placeholder: 'Seleccione una opción',
                dropdownParent: $(modal_clone),
                width: '50px'
            });

            let option  = '<option></option>';
            for(let i in all_services){
                option  += '<option value="'+all_services[i]['id'] +'" data-duracion="'+all_services[i]['duracion_minutos'] +'">'+all_services[i]['nombre']+'</option>'
            }

            $(template_service).find('.select_servicios').append(option).select2({
                placeholder: 'Seleccione',
                dropdownParent: $(modal_clone),
                width: '50px'
            })
            .on('select2:select',function(){
                const id        = $(this).val();
                const duracion  = $(this).closest('.header_service').find('.select_servicios').find('option:selected').data('duracion');

                //  MODIFICAR DURACION DEL LABEL DE SPAN
                $(this).closest('.header_service').find('.span_duracion').text(duracion+' Min.');

                fill_profesionales(template_service,id_locacion_registro,id);
            });

            //  SE VERIFICA SI EL PACIENTE YA TIENE REGISTROS
            if (info_paciente != null){
                $(template_service).find('.select_servicios').val(info_paciente['id_servicio']).trigger('change');
                fill_profesionales(template_service,id_locacion_registro,info_paciente['id_servicio'],info_paciente['id_profesional']);
                for(let i in info_paciente['horarios']){
                    add_template_hours(modal_clone,template_service,info_paciente['horarios'][i]);
                }
            } else {
                $(template_service).find('.div_append_hours').append(template_hours);
            }
            $(modal_clone).find('.div_append_service').append(template_service);
        }

        function add_template_hours(modal_clone,btn_element,info_horario = null){
            count_hours ++;
            let template_hours      = $("#template_hours").clone().removeAttr('id').css('display','flex').addClass('row_hours').attr('id','row_'+count_hours);

            $(template_hours).find('.select_dias').select2({
                placeholder: 'Seleccione una opción',
                dropdownParent: $(modal_clone),
                width: '50px'
            });

            //  MODIFICAR DURACION DEL LABEL DE SPAN
            const duracion  = $(btn_element).find('.select_servicios').find('option:selected').data('duracion');

            if (duracion != null && duracion != ''){
                $(template_hours).find('.span_duracion').text(duracion+' Min.');
                $(template_hours).find('.input_hora_inicio').prop('disabled',false);
            }

            if (info_horario != null){
                $(template_hours).find('.select_dias').val(info_horario['dia']).trigger('change');
                $(template_hours).find('.input_hora_inicio').val(info_horario['hora_inicio']).prop('disabled',false);
                $(template_hours).find('.input_hora_termino').val(info_horario['hora_termino']);
            }

            $(btn_element).find('.div_append_hours').append(template_hours);

            //  SI HAY UN SERVICIO SELECCIONADO, SE PINTARA LA DURACION EN EL REGISTRO

        }

        // Función para inicializar o recargar la tabla
        function cargarTabla() {
            draw    ++;
            if (!table) {
                table = new DataTable('#table_results', {
                    dom: 'lrtip',
                    paging: true,
                    info: true,
                    lengthChange: false,
                    language: translations,
                    ordering: false,
                    serverSide: true,
                    ajax: {
                        url: url_index,
                        method: 'POST',
                        data: function (d) {
                            d.pageSize  = d.length == null || d.length == '' ? 1 : d.length;
                            d.offset    = d.start == null || d.start == '' ? 0 : d.start;
                            d.draw      = draw;
                            d.accion    = 'get_rows';
                            d.clave     = $("#input_clave").val();
                            d.primer_apellido   = $("#input_primer_apellido").val();
                            d.segundo_apellido  = $("#input_segundo_apellido").val();
                            d.nombre            = $("#input_nombre").val();
                            d.id_servicio       = $("#select_servicios").val();
                            d.id_locacion_registro  = $("#select_locaciones").val();
                            d.get_diagnoses         = true;
                        },
                        dataSrc: function (json) {
                            console.log("DataTables Response:", json); // <---- Depuración
                            return json.data;
                        }
                    },
                    columns: [
                        { data: 'clave' }, // Columna 1
                        { data: 'nombre_completo' }, // Columna 1
                        { data: 'celular' }, // Columna 1
                        { data: 'fecha_nacimiento' }, // Columna 1
                        { data: 'edad_actual' }, // Columna 1
                        { data: 'num_servicios' }, // Columna 1
                        { data: 'diagnosticos_registrados' }, // Columna 1
                        { data: 'label_estatus' }, // Columna 1
                        {
                            data: null, 
                            className: "text-center", // Centra el contenido de la celda
                            orderable: false, // Desactiva el ordenamiento para esta columna
                            render: function (data, type, row) {
                                draw    ++;
                                // `data` contiene el objeto completo de la fila
                                // Generamos un botón con un atributo dinámico para identificar la fila
                                let btn_preview = url_preview ?
                                '<button class="btn btn-outline-dark btn-sm btn_preview" data-id="'+data['id']+'" title="'+translations['title_preview'] +'">' +
                                    '<i class="bi bi-search"></i> '+
                                '</button>' : '';
                                
                                let btn_update  = action_update ? 
                                '<button class="btn btn-outline-dark btn-sm btn_edit" data-id="'+data['id']+'" title="'+translations['title_update'] +'">' +
                                    '<i class="bi bi-pencil-fill"></i>'+
                                '</button>' +
                                '<button class="btn btn-outline-dark btn-sm btn_change_status" data-id="'+data['id']+'" data-estatus="'+data['estatus']+'" title="'+translations['title_change'] +'">' +
                                    '<i class="bi bi-arrow-repeat"></i>'+
                                '</button>'+
                                '<button class="btn btn-outline-dark btn-sm btn_diagnoses" data-id="'+data['id']+'" title="'+translations['diagnosis_capture'] +'">' +
                                    '<i class="bi bi-card-list"></i>'+
                                '</button>' 
                                : '';

                                let btn_schedule_appointment    = action_schedule_appointments ? 
                                '<button class="btn btn-outline-dark btn-sm btn_program_date" data-id="'+data['id']+'" data-idlocacionregistro="'+data['id_locacion_registro']+'" data-nombrecompleto="'+data['nombre_completo']+'" title="'+translations['schedule_appointments'] +'">' +
                                    '<i class="bi bi-calendar2-check"></i>'+
                                '</button>'
                                : '';

                                let btn_delete  = action_delete ? 
                                '<button class="btn btn-outline-dark btn-sm btn_delete" data-id="'+data['id']+'" data-clave="'+data['clave']+'" data-activo="'+data['activo']+'" title="'+translations['title_delete'] +'">' +
                                    '<i class="bi bi-trash3-fill"></i>'+
                                '</button>' : '';
                                return btn_preview + btn_schedule_appointment +  btn_update + btn_delete;
                            }
                        }
                    ],
                    createdRow: function (row, data, dataIndex) {
                        // Guardar el objeto completo en la fila como data
                        $(row).data('rowData', data);
                    }
                });
            } else {
                draw    ++;
                table.ajax.reload();
            }
        }

        function show_modal_creacion(data = null){
            let modal_clone = $("#modal_create").clone().show();

            $(modal_clone).find('#select_locaciones').select2({
                placeholder     : 'Seleccione una opción',
                dropdownParent: $(modal_clone)
            });

            //  SI DATA VIENE CON INFORMACION ES EDICION
            if (data != null){
                $(modal_clone).find('#select_locaciones').val(data['id_locacion_registro']).trigger('change');
                $(modal_clone).find('#input_celular').val(data['celular']);
                $(modal_clone).find('#input_primer_apellido').val(data['primer_apellido']);
                $(modal_clone).find('#input_segundo_apellido').val(data['segundo_apellido']);
                $(modal_clone).find('#input_nombre').val(data['nombre']);
                $(modal_clone).find('#input_fecha_nacimiento').val(data['fecha_nacimiento']);
            }

            //  EVENTOS
            $(modal_clone).on('keypress','#input_celular',function(e) {
                if(isNaN(this.value + String.fromCharCode(e.charCode))) 
                return false;
            })
            .on("cut copy paste",function(e){
                e.preventDefault();
            });

            $(modal_clone).on('click','#btnSave',function(){
                let btn =  $(this);
                $(btn).prop('disable',true);

                const form = $(modal_clone).find('#form_modal_create')[0]; // Obtén el elemento DOM
                let flag_error  = false;
                if (form.checkValidity() === false) {
                    $(form).addClass('was-validated');
                    flag_error  = true;
                } else {
                    $(form).removeClass('was-validated');
                }

                //  VALIDAR ESTRUCTURA DE DATOS
                if (parseInt($(modal_clone).find('#input_celular').val().length) != parseInt(10)){
                    console.log('pase1');
                    $(modal_clone).find('#alert_error').find('#msg_error').html(error_list['error_celular']);
                    $(modal_clone).find('#alert_error').addClass('d-flex').show();
                    return false;
                } else {
                    $(modal_clone).find('#alert_error').removeClass('d-flex').hide();
                }

                const fecha_nacimiento  = $(modal_clone).find('#input_fecha_nacimiento').val();

                if (flag_error){
                    return false;
                }

                let obj_info    = {
                    celular             : $(modal_clone).find('#input_celular').val(),
                    primer_apellido     : $(modal_clone).find('#input_primer_apellido').val(),
                    segundo_apellido    : $(modal_clone).find('#input_segundo_apellido').val(),
                    nombre              : $(modal_clone).find('#input_nombre').val(),
                    id_locacion_registro    : $(modal_clone).find('#select_locaciones').val(),
                    label_locacion          : $(modal_clone).find('#select_locaciones').find('option:selected').text(),
                    fecha_nacimiento        : convertirFechaDDMMYYYYaISO(fecha_nacimiento)
                };

                if (data != null){
                    obj_info['id']  = data['id'];
                }

                console.log('obj_info');
                console.log(obj_info);
                //return false;

                //  AJAX SAVE
                $.ajax({
                    url         : data != null ? url_update : url_create,
                    method      : 'POST',
                    dataType    : 'json',
                    data        : {
                        obj_info    : obj_info,
                        accion      : data != null ? 'save_express' : 'create_express',
                        data_old    : data
                    },
                    success     : function(data){
                        $(btn).prop('disabled',false);
                        $(modal_clone).modal('hide');
                        showAlert('success',data);
                        cargarTabla();
                    },
                    error     : function(error){
                        actionJsonError(error,btn);
                    }
                })
            });

            $(modal_clone).modal('show');
        }

        //  MODAL PARA CAPTURA Y EDICION DE DIAGNOSTICOS
        function show_modal_diagnoses(data = null){
            let modal_clone = $("#modal_diagnostico").clone().removeAttr('id');

            if (data != null && Object.keys(data['diagnosticos']).length > 0){
                for(let i in data['diagnosticos']){
                    $(modal_clone).find('#diagnostico_'+data['diagnosticos'][i]['id'])
                        .addClass('bg-success')
                        .find('.input_evidencia')
                        .prop('disabled',false)
                        .prop('checked',data['diagnosticos'][i]['presento_evidencia'] == 1 ? true : false);
                }
            }

            $(modal_clone).find('#nombre_paciente').text(data['nombre_completo']);

            $(modal_clone).on('click','.div_diagnostico',function(event){
                // Evita que el evento se dispare si el clic fue en el input
                if ($(event.target).is('input')) {
                    return;
                }
                if ($(this).hasClass('bg-success')){
                    $(this).removeClass('bg-success');
                    $(this).find('input').prop('disabled',true).prop('checked',false)
                } else {
                    $(this).addClass('bg-success');
                    $(this).find('input').prop('disabled',false);
                }
            });
            
            $(modal_clone).on('click','#btnSave',function(){
                let btn         = $(this);
                $(btn).prop('disabled',true);

                let obj_info    = [];

                $(modal_clone).find('.div_diagnostico.bg-success').each(function(){
                    let id_transtorno       = $(this).data('id');
                    let presento_evidencia  = $(this).find('input').prop('checked') ? 1 : 0;
                    obj_info.push({
                        id_transtorno,
                        presento_evidencia
                    })
                });

                console.log('obj_info',obj_info);

                $.ajax({
                    url     : url_update,
                    method  : 'post',
                    data    : {
                        accion      : 'save_diagnoses',
                        obj_info    : obj_info,
                        id_paciente : data['id'],
                        data_old    : data
                    },
                    success : function(data){
                        showAlert('success','Captura exitosa!');
                        $(modal_clone).modal('hide');
                        cargarTabla();
                    },
                    error   : function(error){
                        actionJsonError(error,btn);
                    }
                });
            })

            $(modal_clone).modal('show');
        }

        function convertirFechaDDMMYYYYaISO(fechaTexto) {
            let partes = [];

            if (fechaTexto.includes('/')) {
                partes = fechaTexto.split('/');
            } else if (fechaTexto.includes('-')) {
                partes = fechaTexto.split('-');
            } else {
                return null; // Formato no reconocido
            }

            if (partes.length !== 3) return null;

            const [dia, mes, anio] = partes;
            return `${anio}-${mes.padStart(2, '0')}-${dia.padStart(2, '0')}`;
        }


    })();  
</script>