<div class="container animate__animated animate__fadeInDown animate__slow">
    <h2 class="text-center">Bienvenido</h2>
    <form>
        <div class="mb-4">
            <label for="username" class="form-label">Usuario</label>
            <input type="text" class="form-control" id="username" placeholder="Ingrese su usuario" required>
        </div>
        <div class="mb-4">
            <label for="password" class="form-label">Contraseña</label>
            <input type="password" class="form-control" id="password" placeholder="Ingrese su contraseña" required>
        </div>
        <div id="alert_error" class="alert alert-danger align-items-center" role="alert" style="display: none;">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                Usuario y/o contraseña invalido
            </div>
        </div>
        <button id="loginForm" type="button" class="btn btn-primary w-100">Ingresar</button>
    </form>
</div>
<script>
    $(document).ready(function() {
        // Capturar el evento submit del formulario
        $('#loginForm').on('click', function(event) {
            let btn = $(this);
            $(btn).prop('disabled',true);
            // Evitar que el formulario se envíe de forma predeterminada
            event.preventDefault();
            
            // Obtener los valores de los campos del formulario
            let username = $('#username').val();
            let password = $('#password').val();

            // Validar los campos (ejemplo simple)
            if (username === '' || password === '') {
                showAlert('danger','Por favor, ingrese todos los campos.');
                $(btn).prop('disabled',false);
                return;
            }

            // Mostrar los valores ingresados (solo para pruebas)
            console.log('Usuario:', username);
            console.log('Contraseña:', password);

            // Aquí puedes enviar los datos al servidor usando AJAX o cualquier otra lógica
            // Ejemplo con AJAX (enviar a una URL ficticia):
            
            $.ajax({
                url: '/login/index',  // URL donde se procesan los datos
                method: 'POST',
                data: {
                    username: username,
                    password: password,
                    action  : 'authenticate'
                },
                success: function(response) {
                    // Procesar respuesta del servidor
                    console.log('success');
                    console.log(response);
                    window.location.href = '/Menu';
                    // Redirigir o mostrar mensaje de éxito
                },
                error: function(error) {
                    // Manejar errores
                    console.log('error');
                    console.log(error);
                    $("#alert_error").addClass('d-flex').show();
                    $(btn).prop('disabled',false);
                }
            });
            

            // Si todo está correcto, enviar el formulario (en este caso lo evitamos por AJAX)
            // this.submit(); // Descomentar si se quiere enviar de manera tradicional después de la validación
        });
    });
</script>