<?php 
use App\Library\FuncionesGlobales;
?>
<style>
    .list-group-item {
      border: none; /* Elimina los bordes */
      cursor: pointer; /* Cambia el cursor al pasar por el div padre */
    }

    .hide{
        display: none;
    }

    .div_label_accion {
        margin-bottom: 5px; /* Reduce el espacio vertical entre los elementos */
        padding: 0; /* Opcional: elimina el relleno interno si es necesario */
    }
</style>
<div class="container mt-4">
    <!-- Section 1: Search Filters -->
    <div id="header_filters" class="card mb-4">
        <div class="card-header">
            <h5><?php echo $translations['html_header_search']; ?></h5>
        </div>
        <div class="card-body">
            <form id="searchForm" class="row g-3">
                <div class="col-md-4">
                    <label for="nameFilter" class="form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave" placeholder="<?php echo $translations['html_title_access_key']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="nameFilter" class="form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" placeholder="<?php echo $translations['html_title_name']; ?>">
                </div>
                <div class="col-md-12 text-end">
                    <button type="button" class="btn btn-primary" id="btnBuscar"><?php echo $translations['html_btn_search']; ?></button>
                    <button type="button" class="btn btn-success" id="btnCrear"><?php echo $translations['html_new']; ?></button>
                    <button type="button" class="btn btn-secondary"><?php echo $translations['html_btn_return']; ?></button>
                </div>
            </form>
        </div>
    </div>

    <!-- Section 2: Data Table -->
    <div class="card">
        <div class="card-header">
            <h5><?php echo $translations['html_header_results']; ?></h5>
        </div>
        <div class="card-body">
            <table id="table_results" class="display table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th><?php echo $translations['html_access_key']; ?></th>
                        <th><?php echo $translations['html_name']; ?></th>
                        <th><?php echo $translations['html_description']; ?></th>
                        <th><?php echo $translations['html_action']; ?></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_create" tabindex="-1" aria-labelledby="label_modal_create" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label_modal_create"><?php echo FuncionesGlobales::UpperString($translations['html_new']); ?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body col-md-12">
        <form>
            <div class="row mb-3">
                <!-- Campo Clave -->
                <div class="col-md-6">
                    <label for="input_clave" class="col-form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave">
                </div>
                <!-- Campo Nombre -->
                <div class="col-md-6">
                    <label for="input_nombre" class="col-form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre">
                </div>
            </div>
            <div class="col-md-12">
                <label for="message-text" class="col-form-label"><?php echo $translations['html_description']; ?></label>
                <textarea class="form-control" id="textarea_description"></textarea>
            </div>
            <div class="container mt-5 col-md-12">
                <!--    LISTA DE PERMISOS   -->
                <div class="list-group div_header_permisos">
                    
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>

<div id="template_padre" style="display:none;">
    <div class="d-flex align-items-center"> <!-- Flex para alinear elementos -->
        <label class="list-group-item parent-option mb-0 me-2"> <!-- Espaciado entre checkbox y texto -->
        <input class="form-check-input me-1" type="checkbox" value="">
        </label>
        <span class="span_controlador"></span> <!-- Texto alineado con el checkbox -->
    </div>
    <div class="ms-4 child-options"></div>
</div>

<label id="template_sublist" class="list-group-item hide div_label_accion" style="display:none;">
    <input class="form-check-input" type="checkbox" value="">
    <span class="span_accion"></span>
</label>

<script>
    //  ENCAPSULACIMIENTO DE CODIGO
var mod_tipo_usuario    = (function(){

    //  URL
    const controller    = '/Tipousuarios';
    const url_index     = controller+"/index";
    const url_create    = controller+"/create";

    //  PERMISOS
    const action_create = '<?php echo $create; ?>';
    const action_update = '<?php echo $update; ?>';
    const action_detele = '<?php echo $delete; ?>';

    //  language
    const tableTranslations = {
        emptyTable: "<?= $translations['table_no_data'] ?>",
        info: "<?= $translations['showing_info'] ?>",
        infoEmpty: "<?= $translations['no_records'] ?>",
        search: "<?= $translations['search'] ?>",
        paginate: {
            first: "<?= $translations['paginate_first'] ?>",
            last: "<?= $translations['paginate_last'] ?>",
            next: "<?= $translations['paginate_next'] ?>",
            previous: "<?= $translations['paginate_previous'] ?>"
        }
    };

    // Variable global para almacenar la instancia de DataTable
    let table;

    // Función para inicializar o recargar la tabla
    // Función para inicializar o recargar la tabla
    function cargarTabla() {
        if (!table) {
            table = new DataTable('#table_results', {
                dom: 'lrtip',
                paging: true,
                info: true,
                lengthChange: false,
                language: tableTranslations,
                ajax: {
                    url: url_index,
                    method: 'POST',
                    data: function (d) {
                        d.pageSize = d.length == null || d.length == '' ? 1 : d.length;
                        d.offset = d.start == null || d.start == '' ? 0 : d.start;
                        d.draw = 1;
                        d.accion = 'get_rows';
                        d.clave = $("#input_clave").val();
                        d.nombre = $("#input_nombre").val();
                    }
                },
                columns: [
                    { data: 'clave' }, // Columna 1
                    { data: 'nombre' }, // Columna 2
                    { data: 'descripcion' }, // Columna 3
                    {
                        data: null, 
                        className: "text-center", // Centra el contenido de la celda
                        orderable: false, // Desactiva el ordenamiento para esta columna
                        render: function (data, type, row) {
                            // `data` contiene el objeto completo de la fila
                            // Generamos un botón con un atributo dinámico para identificar la fila
                            let btn_update  = action_update ? 
                            '<button class="btn btn-warning btn-xs btn_edit">' +
                                '<i class="material-icons">edit</i>'+
                            '</button>' : '';

                            let btn_delete  = action_update ? 
                            '<button class="btn btn-danger btn-xs btn_delete">' +
                                '<i class="material-icons">delete</i>'+
                            '</button>' : '';
                            return btn_update + btn_delete;
                        }
                    }
                ]
            });
        } else {
            table.ajax.reload();
        }
    }

    $(document).ready(function(){
        cargarTabla();

        // Evento click del botón "Buscar"
        $("#header_filters").on('click',"#btnBuscar",function() {
            cargarTabla();
        });

        //  EVENTO PARA OBTENER TODOS LOS PERMISOS PARA CREAR UN TIPO DE USUARIO
        $("#header_filters").on('click',"#btnCrear",function() {
            $.ajax({
                url     : url_index,
                method  : 'POST',
                data    : {
                    accion  : 'get_permisos'
                },
                success : function(data){
                    console.log('data');
                    console.log(data);
                    show_create_modal(data);
                },
                error   : function(error){
                    console.log('error');
                    console.log(error);
                }
            });
        });
    });

    //  FUNCION PARA MOSTRAR MODAL DE CREACION
    function show_create_modal(data){
        let modal_clone = $("#modal_create").clone();
        console.log('dentro de funcion');
        for(let i in data){

            let label_controlador   = data[i][0]['label_controlador'];
            let class_controlador   = 'div_'+data[i][0]['controlador'];

            let div_padre   = $("#template_padre").clone().removeAttr('id').addClass('div_header').attr('id',class_controlador).show();
            $(div_padre).find('.span_controlador').text(label_controlador);
            
            //  SE RECORRE EL ARRAY PARA OBTENER CADA PERMISO DEL CONTROLADOR
            let permisos    = data[i];

            for(let x in permisos){
                let label_accion    = $("#template_sublist").clone().removeAttr('id').show();

                $(label_accion).find('.span_accion').text(permisos[x]['label_accion']);
                $(label_accion).find('input').data('id',permisos[x]['id'])

                $(div_padre).find('.child-options').append(label_accion);
            }

            $(modal_clone).find('.div_header_permisos').append(div_padre);
        }

        //  EVENTOS MODAL
        $(modal_clone).on('click','.span_controlador',function(){
            console.log($(this).closest('.div_header').find('.hide').length);
            if ($(this).closest('.div_header').find('.hide').length > 0){
                $(this).closest('.div_header').find('.div_label_accion').removeClass('hide');
            } else {
                $(this).closest('.div_header').find('.div_label_accion').addClass('hide');
            }
        });

        $(modal_clone).modal('show');
    }
})();
</script>