<?php 
use App\Library\FuncionesGlobales;
?>
<style>
    .list-group-item {
      border: none; /* Elimina los bordes */
      cursor: pointer; /* Cambia el cursor al pasar por el div padre */
    }

    .hide{
        display: none;
    }

    .div_label_accion {
        margin-bottom: 5px; /* Reduce el espacio vertical entre los elementos */
        padding: 0; /* Opcional: elimina el relleno interno si es necesario */
    }
</style>
<div class="container mt-4">
    <!-- Section 1: Search Filters -->
    <div id="header_filters" class="card mb-4">
        <div class="card-header">
            <h5><?php echo $translations['html_header_search']; ?></h5>
        </div>
        <div class="card-body">
            <form id="searchForm" class="row g-3">
                <div class="col-md-4">
                    <label for="nameFilter" class="form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave" placeholder="<?php echo $translations['html_title_access_key']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="nameFilter" class="form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" placeholder="<?php echo $translations['html_title_name']; ?>">
                </div>
                <div class="col-md-12 text-end">
                    <button type="button" class="btn btn-primary" id="btnBuscar"><?php echo $translations['html_btn_search']; ?></button>
                    <button type="button" class="btn btn-success" id="btnCrear"><?php echo $translations['html_new']; ?></button>
                    <button type="button" class="btn btn-secondary"><?php echo $translations['html_btn_return']; ?></button>
                </div> 
            </form>
        </div>
    </div>

    <!-- Section 2: Data Table -->
    <div class="card">
        <div class="card-header">
            <h5><?php echo $translations['html_header_results']; ?></h5>
        </div>
        <div class="card-body">
            <table id="table_results" class="display table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th><?php echo $translations['html_access_key']; ?></th>
                        <th><?php echo $translations['html_name']; ?></th>
                        <th><?php echo $translations['html_description']; ?></th>
                        <th><?php echo $translations['html_status']; ?></th>
                        <th><?php echo $translations['html_action']; ?></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_create" tabindex="-1" aria-labelledby="label_modal_create" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label_modal_create"><?php echo FuncionesGlobales::UpperString($translations['html_new']); ?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body col-md-12">
        <form id="form_modal_create" class="needs-validation" novalidate>
            <div class="row mb-3">
                <!-- Campo Clave -->
                <div class="col-md-6">
                    <label for="input_clave" class="col-form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_access_key']; ?></div>
                </div>
                <!-- Campo Nombre -->
                <div class="col-md-6">
                    <label for="input_nombre" class="col-form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" required>
                    <div class="invalid-feedback"><?php echo $translations['html_error_name']; ?></div>
                </div>
            </div>
            <div class="col-md-12">
                <label for="textarea_description" class="col-form-label"><?php echo $translations['html_description']; ?></label>
                <textarea class="form-control" id="textarea_description"></textarea>
            </div>
            <div class="container mt-5 col-md-12">
                <!-- LISTA DE PERMISOS -->
                <div class="list-group div_header_permisos"></div>
            </div>
            <div id="alert_error_permisos" class="alert alert-danger align-items-center" role="alert" style="display:none;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div>
                    <?php echo $translations['html_error_empty_list']; ?>
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><?php echo $translations['html_btn_cancel']; ?></button>
        <button type="button" id="btnSave" class="btn btn-primary"><?php echo $translations['html_btn_save']; ?></button>
      </div>
    </div>
  </div>
</div>


<div id="template_padre" style="display:none;">
    <div class="d-flex align-items-center"> <!-- Flex para alinear elementos -->
        <label class="list-group-item parent-option mb-0 me-2"> <!-- Espaciado entre checkbox y texto -->
        <input class="form-check-input me-1 header_check" type="checkbox" value="">
        </label>
        <span class="span_controlador" style="cursor: pointer;"></span> <!-- Texto alineado con el checkbox -->
    </div>
    <div class="ms-4 child-options"></div>
</div>

<label id="template_sublist" class="list-group-item hide div_label_accion" style="display:none;">
    <input class="form-check-input check_sublist" type="checkbox" value="">
    <span class="span_accion"></span>
</label>

<script>
    //  ENCAPSULACIMIENTO DE CODIGO
var mod_tipo_usuario    = (function(){
    let draw            = 0;
    //  URL
    const controller    = '/Tipousuarios';
    const url_index     = controller+"/index";
    const url_create    = controller+"/create";
    const url_delete    = controller+"/delete";

    //  PERMISOS
    const action_create = '<?php echo $create; ?>';
    const action_update = '<?php echo $update; ?>';
    const action_detele = '<?php echo $delete; ?>';

    //  language
    const tableTranslations = {
        emptyTable: "<?= $translations['table_no_data'] ?>",
        info: "<?= $translations['showing_info'] ?>",
        infoEmpty: "<?= $translations['no_records'] ?>",
        search: "<?= $translations['search'] ?>",
        paginate: {
            first: "<?= $translations['paginate_first'] ?>",
            last: "<?= $translations['paginate_last'] ?>",
            next: "<?= $translations['paginate_next'] ?>",
            previous: "<?= $translations['paginate_previous'] ?>"
        }
    };

    // Variable global para almacenar la instancia de DataTable
    let table;

    // Función para inicializar o recargar la tabla
    // Función para inicializar o recargar la tabla
    function cargarTabla() {
        //showBlockCargando();
        draw    ++;
        if (!table) {
            table = new DataTable('#table_results', {
                dom: 'lrtip',
                paging: true,
                info: true,
                lengthChange: false,
                language: tableTranslations,
                ajax: {
                    url: url_index,
                    method: 'POST',
                    data: function (d) {
                        d.pageSize  = d.length == null || d.length == '' ? 1 : d.length;
                        d.offset    = d.start == null || d.start == '' ? 0 : d.start;
                        d.draw      = draw;
                        d.accion    = 'get_rows';
                        d.clave     = $("#input_clave").val();
                        d.nombre    = $("#input_nombre").val();
                    }
                },
                columns: [
                    { data: 'clave' }, // Columna 1
                    { data: 'nombre' }, // Columna 2
                    { data: 'descripcion' }, // Columna 3
                    { data: 'label_estatus' }, // Columna 4
                    {
                        data: null, 
                        className: "text-center", // Centra el contenido de la celda
                        orderable: false, // Desactiva el ordenamiento para esta columna
                        render: function (data, type, row) {
                            // `data` contiene el objeto completo de la fila
                            // Generamos un botón con un atributo dinámico para identificar la fila
                            let btn_update  = action_update ? 
                            '<button class="btn btn-warning btn-xs btn_edit" data-id="'+data['id']+'">' +
                                '<i class="material-icons">edit</i>'+
                            '</button>' : '';

                            let btn_delete  = action_update ? 
                            '<button class="btn btn-danger btn-xs btn_delete" data-id="'+data['id']+'" data-activo="'+data['activo']+'">' +
                                '<i class="material-icons">delete</i>'+
                            '</button>' : '';
                            return btn_update + btn_delete;
                        }
                    }
                ]
            });
        } else {
            table.ajax.reload();
        }

        //hideBlockCargando();
    }

    $(document).ready(function(){
        cargarTabla();

        // Evento click del botón "Buscar"
        $("#header_filters").on('click',"#btnBuscar",function() {
            cargarTabla();
        });

        //  EVENTO PARA OBTENER TODOS LOS PERMISOS PARA CREAR UN TIPO DE USUARIO
        $("#header_filters").on('click',"#btnCrear",function() {
            $.ajax({
                url     : url_index,
                method  : 'POST',
                data    : {
                    accion  : 'get_permisos'
                },
                success : function(data){
                    console.log('data');
                    console.log(data);
                    show_create_modal(data);
                },
                error   : function(error){
                    console.log('error');
                    console.log(error);
                }
            });
        });

        //  EVENTO BOTON EDITAR
        $("#table_results").on('click','.btn_edit',function(){
            //showBlockCargando();
        });

        $("#table_results").on('click','.btn_delete',async function() {

            const id        = $(this).data('id');
            const activo    = $(this).data('activo');
            const msg       = activo == 1 ? 'borrar' : 'modificar';
            const respuesta = await window.modalConfirm('&iquest;Desea '+msg+' el registro?');

            if (respuesta) {
                $.ajax({
                    url     : url_delete,
                    method  : 'POST',
                    data    : {
                        id  : id
                    },
                    success : function(data){
                        console.log('data');
                        console.log(data);
                        showAlert('success',"Borrado exitoso!");
                        cargarTabla();
                    },
                    error   : function(error){
                        console.log('error');
                        console.log(error);
                        showAlert('danger',error.responseText);
                    }
                });
            }
        });
    });

    //  FUNCION PARA MOSTRAR MODAL DE CREACION
    function show_create_modal(data){
        let modal_clone = $("#modal_create").clone();
        console.log('dentro de funcion');
        for(let i in data){

            let label_controlador   = data[i][0]['label_controlador'];
            let class_controlador   = 'div_'+data[i][0]['controlador'];

            let div_padre   = $("#template_padre").clone().removeAttr('id').addClass('div_header').attr('id',class_controlador).show();
            $(div_padre).find('.span_controlador').text(label_controlador);
            
            //  SE RECORRE EL ARRAY PARA OBTENER CADA PERMISO DEL CONTROLADOR
            let permisos    = data[i];

            for(let x in permisos){
                let label_accion    = $("#template_sublist").clone().removeAttr('id').show();

                $(label_accion).find('.span_accion').text(permisos[x]['label_accion']);
                $(label_accion).find('input').data('id',permisos[x]['id'])

                $(div_padre).find('.child-options').append(label_accion);
            }

            $(modal_clone).find('.div_header_permisos').append(div_padre);
        }

        //  EVENTOS MODAL
        $(modal_clone).on('click','.span_controlador',function(){
            console.log($(this).closest('.div_header').find('.hide').length);
            if ($(this).closest('.div_header').find('.hide').length > 0){
                $(this).closest('.div_header').find('.div_label_accion').removeClass('hide');
            } else {
                $(this).closest('.div_header').find('.div_label_accion').addClass('hide');
            }
        });

        //  EVENTO PARA CHECK
        $(modal_clone).on('click','.header_check',function(){
            let status_check    = $(this).prop('checked');

            $(this).closest('.div_header').find('.check_sublist').prop('checked',status_check);
        });

        $(modal_clone).on('click','.check_sublist',function(){
            let count_elements  = $(this).closest('.child-options').find('.check_sublist').length;

            console.log('checked');
            console.log($(this).closest('.child-options').find('.check_sublist:checked').length);
            if ($(this).closest('.child-options').find('.check_sublist:checked').length == count_elements){
                console.log('todos checked');
                $(this).closest('.div_header').find('.header_check').prop('checked',true);
            }

            if ($(this).closest('.child-options').find('.check_sublist:checked').length == 0){
                console.log('ninguno checked');
                $(this).closest('.div_header').find('.header_check').prop('checked',false);
            }
        });

        // Agregar evento al botón de envío
        $(modal_clone).on('click','#btnSave',function () {
            let btn = $(this);
            $(btn).prop('disabled',true);
            // Seleccionar el formulario dentro del modal
            const form = $(modal_clone).find('#form_modal_create')[0]; // Obtén el elemento DOM
            let flag_error  = false;
            if (form.checkValidity() === false) {
                // Si el formulario no es válido, muestra mensajes de error
                $(form).addClass('was-validated');
                flag_error  = true;
            } else {
                $(form).removeClass('was-validated');
            }

            if ($(modal_clone).find('.check_sublist:checked').length == 0){
                $(modal_clone).find('#alert_error_permisos').addClass('d-flex').show();
            } else {
                $(modal_clone).find('#alert_error_permisos').removeClass('d-flex').hide();
            }

            let permissions_list    = [];
            $(modal_clone).find('.check_sublist:checked').each(function(){
                permissions_list.push($(this).data('id'));
            });

            console.log('list');
            console.log(permissions_list);

            //  AJAX SAVE
            $.ajax({
                url         : url_create,
                method      : 'POST',
                dataType    : 'json',
                data        : {
                    clave   : $(modal_clone).find('#input_clave').val(),
                    nombre  : $(modal_clone).find('#input_nombre').val(),
                    descripcion     : $(modal_clone).find('#textarea_descripcion').val(),
                    lista_permisos  : permissions_list
                },
                success     : function(data){
                    console.log('success');
                    console.log(data);
                    $(btn).prop('disabled',false);
                    $(modal_clone).modal('hide');
                    showAlert('success',data);
                    cargarTabla();
                },
                error     : function(error){
                    console.log('error');
                    console.log(error);
                    $(btn).prop('disabled',false);
                    showAlert('danger',error.responseText);
                }
            })
        });

        // Prevenir envío por defecto si el formulario es inválido
        $(modal_clone).find('#form_modal_create').on('submit', function (event) {
            if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
            }
        });

        $(modal_clone).modal('show');
    }
})();
</script>