<?php 
use App\Library\FuncionesGlobales;
?>
<style>
    .list-group-item {
      border: none; /* Elimina los bordes */
      cursor: pointer; /* Cambia el cursor al pasar por el div padre */
    }

    .hide{
        display: none;
    }

    .div_label_accion {
        margin-bottom: 5px; /* Reduce el espacio vertical entre los elementos */
        padding: 0; /* Opcional: elimina el relleno interno si es necesario */
    }

    .div_check {
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da; /* Color del borde */
        border-radius: 0.375rem; /* Bordes redondeados */
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        max-width: calc(100% - 1px); /* Reduce el ancho en 1px */
        cursor: pointer;
    }

    .hide {
        display:none;
    }

    .div_header_horario_fijo .table-responsive {
        max-height: 400px; /* ajusta según lo que necesites */
        overflow-y: auto;
    }

    .div_header_horario_fijo .table-responsive thead th {
        position: sticky;
        top: 0;
        z-index: 2;
        background-color: #fff; /* importante para que no se vea el contenido pasando por debajo */
    }

    .div_header_horario_fijo tbody td {
        text-align: center;
        vertical-align: middle;
    }

    .modal_transferir .fix-padding span {
        display: block;
        color: #495057;
        font-size: 0.95rem;
    }

</style>
<div class="container mt-4">
    <!-- Section 1: Search Filters -->
    <div>
        <h2><?php echo FuncionesGlobales::UpperString($translations['html_title_professionals']); ?></h2>
    </div>
    <div id="header_filters" class="card mb-4">
        <div class="card-header">
            <h5><?php echo $translations['html_header_search']; ?></h5>
        </div>
        <div class="card-body">
            <form id="searchForm" class="row g-3">
                <div class="col-md-4">
                    <label for="input_clave" class="form-label"><?php echo $translations['html_access_key']; ?></label>
                    <input type="text" class="form-control" id="input_clave" placeholder="<?php echo $translations['html_title_access_key']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="input_nombre" class="form-label"><?php echo $translations['html_name']; ?></label>
                    <input type="text" class="form-control" id="input_nombre" placeholder="<?php echo $translations['html_title_name']; ?>">
                </div>
                <div class="col-md-4">
                    <label for="select_servicios" class="form-label"><?php echo $translations['html_services']; ?></label>
                    <select id="select_servicios" class="form-select" aria-label="Default select example">
                        <option></option>
                        <?php foreach($arr_servicios as $servicio): ?>
                            <option value="<?php echo $servicio['id']; ?>"><?php echo $servicio['nombre']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-12 text-end">
                    <button type="button" class="btn btn-outline-dark" id="btnBuscar">
                        <i class="bi bi-search"></i> 
                        <?php echo $translations['html_btn_search']; ?>
                    </button>
                    <button type="button" class="btn btn-outline-dark" id="btnCrear">
                        <i class="bi bi-plus-lg"></i> 
                        <?php echo $translations['html_new']; ?>
                    </button>
                </div> 
            </form>
        </div>
    </div>

    <!-- Section 2: Data Table -->
    <div class="card">
        <div class="card-header">
            <h5><?php echo $translations['html_header_results']; ?></h5>
        </div>
        <div class="card-body">
            <table id="table_results" class="display table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th><?php echo $translations['html_access_key']; ?></th>
                        <th><?php echo $translations['html_name']; ?></th>
                        <th><?php echo $translations['html_user_type']; ?></th>
                        <th><?php echo $translations['html_status']; ?></th>
                        <th><?php echo $translations['html_action']; ?></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div class="modal fade modal-lg" id="modal_schedule_availability" tabindex="-1" aria-labelledby="label_modal_schedule_availability" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label_modal_schedule_availability"><?php echo $translations['html_schedule_availability']; ?></h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body col-md-12">
        <form id="form_modal_create" class="needs-validation" novalidate>
            <div class="row d-flex align-items-center">
                <div class="col-auto">
                    <label for="select_locaciones" class="form-label me-2"><?php echo $translations['html_locations']; ?></label>
                </div>
                <div class="col-md-4">
                    <select id="select_locaciones" class="form-select select_locaciones" aria-label="Default select example">
                        <option></option>
                    </select>
                </div>
            </div>

            <div class="row col-12 align-items-center" style="padding-top: 5px;">
                <h5><?php echo $translations['html_opennig_hours_locations']; ?></h5>
                <div class="col-2">
                    <label for="input_hora_inicio" class="col-form-label"><?php echo $translations['html_starting_hour']; ?></label>
                </div>
                <div class="col-2">
                    <label for="input_hora_termino" class="col-form-label"><?php echo $translations['html_ending_hour']; ?></label>
                </div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_monday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_thuesday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_wednesday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_thursday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_friday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_saturday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_sunday']; ?></label></div>
                <div class="col-1">Acci&oacute;n</div>
            </div>
            <div class="row rows_table_locaciones" style="max-height:100px;overflow: scroll;">
                
            </div>
            <h5 class="border-top my-3"><?php echo $translations['html_title_professional']; ?></h5>
            <div class="col-md-4 fix-padding">
                <label for="btn_add_service" class="form-label"><?php echo $translations['html_title_add_hour']; ?></label>
                <button type="button" id="btn_add_hours" class="btn btn-outline-dark btn_add_hours" disabled><i class="bi bi-plus"></i></button>
            </div>
            <div class="row col-12 align-items-center" style="padding-top: 5px;">
                <div class="col-2">
                    <label for="input_hora_inicio" class="col-form-label"><?php echo $translations['html_starting_hour']; ?></label>
                </div>
                <div class="col-2">
                    <label for="input_hora_termino" class="col-form-label"><?php echo $translations['html_ending_hour']; ?></label>
                </div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_monday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_thuesday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_wednesday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_thursday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_friday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_saturday']; ?></label></div>
                <div class="col-1"><label class="col-form-label"><?php echo $translations['html_abre_sunday']; ?></label></div>
                <div class="col-1">Acci&oacute;n</div>
            </div>
            <div class="row rows_table" style="max-height:100px;overflow: scroll;">
                
            </div>

            
            <div id="alert_error" class="alert alert-danger align-items-center m-2" role="alert" style="display:none;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div id="msg_error">
                    
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal"><?php echo $translations['html_btn_cancel']; ?></button>
        <button type="button" id="btnSave" class="btn btn-primary"><?php echo $translations['html_btn_save']; ?></button>
      </div>
    </div>
  </div>
</div>

<div id="template_horas" class="row col-12 hide div_header_hours" style="padding-top:5px;">
    <div class="col-2">
        <input type="time" step="60" class="form-control input_hora_inicio" required>
        <div class="invalid-feedback"><?php echo $translations['html_error_starting_hour']; ?></div>
    </div>
    <div class="col-2">
        <input type="time" step="60" class="form-control input_hora_termino" required>
        <div class="invalid-feedback"><?php echo $translations['html_error_ending_hour']; ?></div>
    </div>
    <div class="col-1 rounded border div_check dia_1" data-dia="1"></div>
    <div class="col-1 rounded border div_check dia_2" data-dia="2"></div>
    <div class="col-1 rounded border div_check dia_3" data-dia="3"></div>
    <div class="col-1 rounded border div_check dia_4" data-dia="4"></div>
    <div class="col-1 rounded border div_check dia_5" data-dia="5"></div>
    <div class="col-1 rounded border div_check dia_6" data-dia="6"></div>
    <div class="col-1 rounded border div_check dia_7" data-dia="7"></div>
    <div class="col-1"><button type="button" class="btn btn-outline-danger btn_delete_hours">X</button></div>
</div>

<div class="modal fade modal-xl" id="modal_horario_fjo" tabindex="-1" aria-labelledby="label_save_class" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen-xl-down">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal_ver_cita_fuera_horario"><?php echo FuncionesGlobales::UpperString($translations['html_fixed_schedule']); ?></h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form_modal_create" class="needs-validation" novalidate>
            <div class="mb-3 div_header_horario_fijo">
                <div class="table-responsive">
                    <table class="table_citas table table-striped">
                        <thead>
                        <tr>
                                <th scope="col" style="text-align: center;"><?php echo $translations['html_day']; ?></th>
                                <th scope="col" style="text-align: center;"><?php echo $translations['html_assigned_schedule']; ?></th>
                                <th scope="col" style="text-align: center;"><?php echo $translations['html_title_patient']; ?></th>
                                <th scope="col" style="text-align: center;"><?php echo $translations['html_service']; ?></th>
                                <th scope="col" style="text-align: center;"><?php echo $translations['html_options']; ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal"><?php echo $translations['html_btn_cancel']; ?></button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade modal_transferir" id="modal_transferir" tabindex="-1" aria-labelledby="label_modal_transferir" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label_modal_transferir"><?php echo FuncionesGlobales::UpperString($translations['html_transfer_appointment']); ?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body col-md-12">
        <form id="form_modal_create" class="needs-validation" novalidate>
            <div class="row mb-3">
                <div class="col-md-6 fix-padding">
                    <label for="locacion" class="form-label"><?php echo $translations['html_location']; ?></label>
                    <span id="locacion"></span>
                </div>                
                <!-- Campo Clave -->
                <div class="col-md-6 fix-padding">
                    <label for="nombre_paciente" class="form-label"><?php echo $translations['html_title_patient']; ?></label>
                    <span id="nombre_paciente"></span>
                </div> 
                <!-- Campo Nombre -->
                <div class="col-md-6 fix-padding">
                    <label for="servicio" class="form-label"><?php echo $translations['html_service']; ?></label>
                    <span id="servicio"></span>
                </div> 
                <div class="col-md-6 fix-padding">
                    <label for="horario" class="form-label">Horario</label>
                    <span id="horario"></span>
                </div> 
                <div class="col-md-6 fix-padding">
                    <label for="profesional_actual" class="form-label"><?php echo $translations['html_appointment_professional']; ?></label>
                    <span id="profesional_actual"></span>
                </div> 
                <!-- Campo fecha nacimiento -->
                <div class="col-md-12" style="padding-bottom: 16px;">
                    <label for="select_profesionales" class="col-form-label"><?php echo $translations['html_error_professional']; ?></label>
                    <select id="select_profesionales" class="form-control">
                        
                    </select>
                </div>
            
            <div id="alert_error" class="alert alert-danger align-items-center" role="alert" style="display:none;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div id="msg_error">
                    
                </div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal"><?php echo $translations['html_btn_cancel']; ?></button>
        <button type="button" id="btnSave" class="btn btn-primary"><?php echo $translations['html_btn_save']; ?></button>
      </div>
    </div>
  </div>
</div>

<script>
    let module_profesionale = (function(){
        let draw            = 1;
        let count_hours     = 0;
        //  URL
        const controller    = '/Profesionales';
        const url_index     = controller+"/index";
        const url_create    = controller+"/create";
        const url_delete    = controller+"/delete";
        const url_update    = controller+"/update";
        const url_preview   = controller+"/preview";

        //  PERMISOS
        const action_create = '<?php echo $create; ?>';
        const action_update = '<?php echo $update; ?>';
        const action_delete = '<?php echo $delete; ?>';

        //  language
        const translations  = {
            emptyTable: "<?= $translations['table_no_data'] ?>",
            info: "<?= $translations['showing_info'] ?>",
            infoEmpty: "<?= $translations['no_records'] ?>",
            search: "<?= $translations['search'] ?>",
            paginate: {
                first: "<?= $translations['paginate_first'] ?>",
                last: "<?= $translations['paginate_last'] ?>",
                next: "<?= $translations['paginate_next'] ?>",
                previous: "<?= $translations['paginate_previous'] ?>"
            },
            title_update    : "<?= $translations['html_edit_record'] ?>",
            title_delete    : "<?= $translations['html_delete_record'] ?>",
            title_preview   : "<?= $translations['html_preview_record'] ?>",
            title_change    : "<?= $translations['html_active_deactivate'] ?>",
            confirm_delete  : "<?= $translations['html_confirm_delete']?>",
            confirm_update  : "<?= $translations['html_confirm_update']?>",
            schedule_availability   : "<?= $translations['html_schedule_availability']?>",
            view_fixed_schedule     : "<?= $translations['html_view_fixed_schedule'] ?>",
        };

        //  LISTA DE ERRORES EN MODAL
        const error_list = {
            sin_permisos    : "<?php echo $translations['html_error_empty_list']; ?>",
            error_email     : "<?php echo $translations['html_error_email']; ?>",
            error_celular   : "<?php echo $translations['html_error_cellphone']; ?>",
            error_contrasena    : "<?php echo $translations['html_error_different_password']; ?>",
            error_length_contrasena : "<?php echo $translations['html_error_length_password']; ?>",
            error_empty_days            : "<?php echo $translations['html_error_empty_days']; ?>",
            error_minus_ending_date     : "<?php echo $translations['html_error_minus_ending_date']; ?>",error_less_one_opening_hour : "<?php echo $translations['html_error_less_one_opening_hour']; ?>",
            error_opening_hours         : "<?php echo $translations['html_error_opening_hours']; ?>",//
            error_range_allowed         : "<?php echo $translations['html_error_range_allowed']; ?>",//
        }

        // Variable global para almacenar la instancia de DataTable
        let table;

        $(document).ready(function(){

            cargarTabla();

            selectToSelect2($("#header_filters"),"select_servicios");

            $("#header_filters").on('click',"#btnCrear",function(){
                window.location.href = '/Profesionales/create';
            });

            $("#table_results").on('click','.btn_delete',async function() {

                const id        = $(this).data('id');
                const clave     = $(this).data('clave');
                const respuesta = await window.modalConfirm(translations['confirm_delete']);
                let btn         = $(this);

                $(btn).prop('disabled',true);

                if (respuesta) {
                    $.ajax({
                        url     : url_delete,
                        method  : 'POST',
                        data    : {
                            id  : id,
                            clave           : clave
                        },
                        success : function(data){
                            console.log('data');
                            console.log(data);
                            $(btn).prop('disabled',false);
                            showAlert('success',"Borrado exitosa!");
                            cargarTabla();
                        },
                        error   : function(error){
                            actionJsonError(error,btn);
                        }
                    });
                } else {
                    $(btn).prop('disabled',false);
                }
            });

            //  EVENTO BOTON EDITAR
            $("#table_results").on('click','.btn_change_status',async function(){
                const id        = $(this).data('id');
                const estatus   = $(this).data('estatus');
                const clave     = $(this).data('clave');
                let btn         = $(this);
                $(btn).prop('disabled',true);
                console.log('id',id);

                const respuesta = await window.modalConfirm(translations['confirm_update']);

                $(btn).prop('disabled',true);

                if (respuesta) {
                    $.ajax({
                        url     : url_update,
                        method  : 'POST',
                        data    :  {
                            accion  : 'change_status',
                            id      : id,
                            estatus : estatus,
                            clave   : clave
                        },
                        success : function(data){
                            console.log('data');
                            console.log(data);
                            $(btn).prop('disabled',false);
                            showAlert('success',"Edici&oacute;n exitosa!");
                            cargarTabla();
                        },
                        error   : function(error){
                            actionJsonError(error,btn);
                        }
                    });
                } else {
                    $(btn).prop('disabled',false);
                }
            });

            //  EVENTO BOTON EDITAR
            $("#table_results").on('click','.btn_ver_horario_fijo',async function(){
                const id        = $(this).data('id');
                const clave     = $(this).data('clave');
                let btn         = $(this);
                $(btn).prop('disabled',true);

                $.ajax({
                    url     : url_update,
                    method  : 'POST',
                    data    :  {
                        accion  : 'get_horario_fijo',
                        id_profesional  : id,
                        clave           : clave
                    },
                    success : function(data){
                        console.log('data');
                        console.log(data);
                        $(btn).prop('disabled',false);
                        show_modal_horario_fijo(data,btn);
                        
                    },
                    error   : function(error){
                        actionJsonError(error,btn);
                    }
                });
            });

            // Evento click del botón "Buscar"
            $("#header_filters").on('click',"#btnBuscar",function() {
                cargarTabla();
            });

            //  EVENTO BOTON EDITAR
            $("#table_results").on('click','.btn_edit',function(){
                const id        = $(this).data('id');
                let btn     = $(this);
                $(btn).prop('disabled',true);
                window.location.href = '/Profesionales/update/'+id;
            });

            //  EVENTO BOTON EDITAR
            $("#table_results").on('click','.btn_preview',function(){
                const id        = $(this).data('id');
                let btn     = $(this);
                $(btn).prop('disabled',true);
                window.location.href = '/Profesionales/preview/'+id;
            });

            $("#table_results").on('click','.btn_schedule_availability',function(){
                const id        = $(this).data('id');
                const clave     = $(this).data('clave');
                const nombre    = $(this).data('nombre');
                let btn         = $(this);
                $(btn).prop('disabled',true);
                $.ajax({
                    url     : url_update,
                    method  : 'POST',
                    data    :  {
                        accion  : 'get_locaciones',
                        id      : id
                    },
                    success : function(data){
                        console.log('data');
                        console.log(data);
                        $(btn).prop('disabled',false);
                        showModalScheduleAvailability(data,id,clave,nombre);
                        
                    },
                    error   : function(error){
                        actionJsonError(error,btn);
                    }
                });
            });

            //  EL ENTER EJECUTA EL BUSCAR SOLO SI NO HAY UN MODAL VISIBLE
            $(document).on('keydown', function(e) {
                if ($(document).find('.modal:visible').length == 0 && e.key === 'Enter') {
                    $("#btnBuscar").trigger('click');
                }
            });
        });

        // Función para inicializar o recargar la tabla
        function cargarTabla() {
            draw    ++;
            if (!table) {
                table = new DataTable('#table_results', {
                    dom: 'lrtip',
                    paging: true,
                    info: true,
                    lengthChange: false,
                    language: translations,
                    ordering: false,
                    serverSide: true,
                    ajax: {
                        url: url_index,
                        method: 'POST',
                        data: function (d) {
                            d.pageSize  = d.length == null || d.length == '' ? 1 : d.length;
                            d.offset    = d.start == null || d.start == '' ? 0 : d.start;
                            d.draw      = draw;
                            d.accion    = 'get_rows';
                            d.clave     = $("#input_clave").val();
                            d.nombre    = $("#input_nombre").val();
                            d.id_servicio   = $("#select_servicios").val()
                        },
                        dataSrc: function (json) {
                            console.log("DataTables Response:", json); // <---- Depuración
                            return json.data;
                        }
                    },
                    columns: [
                        { data: 'clave' }, // Columna 1
                        { data: 'nombre_completo' }, // Columna 1
                        { data: 'nombre_tipo_usuario' }, // Columna 1
                        { data: 'label_estatus_usuario' }, // Columna 1
                        {
                            data: null, 
                            className: "text-center", // Centra el contenido de la celda
                            orderable: false, // Desactiva el ordenamiento para esta columna
                            render: function (data, type, row) {
                                draw    ++;
                                // `data` contiene el objeto completo de la fila
                                // Generamos un botón con un atributo dinámico para identificar la fila
                                let btn_preview = url_preview ?
                                '<button class="btn btn-outline-dark btn-sm btn_preview" data-id="'+data['id']+'" title="'+translations['title_preview'] +'">' +
                                    '<i class="bi bi-search"></i> '+
                                '</button>' : '';
                                
                                let btn_update  = action_update ? 
                                '<button class="btn btn-outline-dark btn-sm btn_edit" data-id="'+data['id']+'" title="'+translations['title_update'] +'">' +
                                    '<i class="bi bi-pencil-fill"></i>'+
                                '</button>' +
                                '<button class="btn btn-outline-dark btn-sm btn_schedule_availability" data-id="'+data['id']+'" data-clave="'+data['clave']+'" data-nombre="'+(data['primer_apellido']+' '+data['segundo_apellido']+' '+data['nombre'])+'" title="'+translations['schedule_availability'] +'">' +
                                    '<i class="bi bi-calendar2-event"></i>'+
                                '</button>' +
                                '<button class="btn btn-outline-dark btn-sm btn_change_status" data-id="'+data['id']+'" data-estatus="'+data['estatus']+'" data-clave="'+data['clave']+'" title="'+translations['title_change'] +'">' +
                                    '<i class="bi bi-arrow-repeat"></i>'+
                                '</button>' +
                                '<button class="btn btn-outline-dark btn-sm btn_ver_horario_fijo" data-id="'+data['id']+'"  title="'+translations['view_fixed_schedule'] +'">' +
                                    '<i class="bi bi-calendar-week-fill"></i>'+
                                '</button>'
                                
                                : '';

                                let btn_delete  = action_delete ? 
                                '<button class="btn btn-outline-dark btn-sm btn_delete" data-id="'+data['id']+'" data-clave="'+data['clave']+'" data-activo="'+data['activo']+'" title="'+translations['title_delete'] +'">' +
                                    '<i class="bi bi-trash3-fill"></i>'+
                                '</button>' : '';
                                return btn_preview + btn_update + btn_delete;
                            }
                        }
                    ]
                });
            } else {
                draw    ++;
                table.ajax.reload();
            }
        }

        function ajax_seach_horario_atencion(modal_clone,id_profesional){
            let value   = $(modal_clone).find("#select_locaciones").val();
            //  AJAX PARA BUSCAR LOS HORARIOS DE ATENCION
            $.ajax({
                url     : url_update,
                method  : 'post',
                data    : {
                    id_locacion     : value,
                    id_profesional  : id_profesional,
                    accion          : 'get_opening_hours'
                },
                success : function(data){
                    console.log('data');
                    console.log(data);
                    $(modal_clone).find('.rows_table_locaciones').html('');
                    $(modal_clone).find('.rows_table').html('');
                    let horario_locacion    = data['locacion'];
                    for(let i in horario_locacion){
                        let row_clone   = $("#template_horas").clone().removeClass('div_header_hours').addClass('div_header_hours_locaciones').removeAttr('id').removeClass('hide').attr('id','header_'+count_hours);
                        $(row_clone).find('.input_hora_inicio').val(horario_locacion[i]['hora_inicio']).prop('disabled',true);
                        $(row_clone).find('.input_hora_termino').val(horario_locacion[i]['hora_termino']).prop('disabled',true);
                        $(row_clone).find('.btn_delete_hours').hide();

                        let dias    = horario_locacion[i]['dias'];

                        for(let x in dias){
                            $(row_clone).find('.dia_'+dias[x]['dia']).addClass('selected').addClass('bg-primary');
                        }

                        $(row_clone).find('.div_check').removeClass('div_check');
                        $(modal_clone).find('.rows_table_locaciones').append(row_clone);
                        count_hours ++;
                    }

                    if (data['profesional'].length == 0){
                        let row_clone   = $("#template_horas").clone().removeAttr('id').removeClass('hide').attr('id','header_'+count_hours);
                        $(modal_clone).find('.rows_table').append(row_clone);
                        count_hours ++;
                    } else {
                        let profesional = data['profesional'];
                        for(let i in profesional){
                            let row_clone   = $("#template_horas").clone().removeClass('div_header_hours').addClass('div_header_hours').removeAttr('id').removeClass('hide').attr('id','header_'+count_hours);
                            $(row_clone).find('.input_hora_inicio').val(profesional[i]['hora_inicio']);
                            $(row_clone).find('.input_hora_termino').val(profesional[i]['hora_termino']);

                            let dias    = profesional[i]['dias'];

                            for(let x in dias){
                                $(row_clone).find('.dia_'+dias[x]['dia']).addClass('selected').addClass('bg-primary');
                            }

                            $(row_clone).find('.div_check').removeClass('div_check');
                            $(modal_clone).find('.rows_table').append(row_clone);
                            count_hours ++;
                        }
                    }

                    $(modal_clone).find('.btn_add_hours').prop('disabled',false);

                },
                error   : function(error){
                    console.log('error');
                    console.log(error);
                    actionJsonError(error);
                    $(modal_clone).modal('hide');
                }
            });
        }

        function showModalScheduleAvailability(locaciones,id_profesional,clave,nombre){

            let modal_clone = $("#modal_schedule_availability").clone().show();

            let option  = '';
            for(let i in locaciones){
                option  += '<option value="'+locaciones[i]['id']+'">'+locaciones[i]['nombre']+'</option>'
            }

            $(modal_clone).find('.select_locaciones').append(option);

            $(modal_clone).find('.select_locaciones').select2({
                placeholder: 'Seleccione una opción',
                dropdownParent: $(modal_clone),
                width: '50px'
            }).on('select2:select',function(){
                ajax_seach_horario_atencion(modal_clone,id_profesional);
            });

            if (Object.keys(locaciones).length == 1){
                $(modal_clone).find('.select_locaciones').val(locaciones[0]['id']).trigger('change');
                $(modal_clone).find('.select_locaciones').prop('disabled',true);
                ajax_seach_horario_atencion(modal_clone,id_profesional);
            }

            //  EVENTO PARA AGREGAR DIV DE HORAS
            $(modal_clone).on('click','.btn_add_hours',function(){
                let row_clone   = $("#template_horas").clone().removeAttr('id').removeClass('hide').attr('id','header_'+count_hours);
                $(modal_clone).find('.rows_table').append(row_clone);
                count_hours ++;
            });

            //  EVENTO PARA BORRAR DIV DE HORAS
            $(modal_clone).on('click','.btn_delete_hours',function(){
                $(this).closest('.div_header_hours').remove();
            });

            //  EVENTOS PARA EFECTO HOVER
            $(modal_clone).on('mouseenter', '.div_check', function() {
                if($(this).hasClass('selected')){
                    return false;
                }
                $(this).addClass('bg-primary');
            });

            $(modal_clone).on('mouseleave', '.div_check', function() {
                if($(this).hasClass('selected')){
                    return false;
                }
                $(this).removeClass('bg-primary');
            });

            //  EVENTO PARA SELECCIONAR UN DIA
            $(modal_clone).on('click','.div_check',function(){
                if ($(this).hasClass('selected')){
                    $(this).removeClass('selected').removeClass('bg-primary');
                } else {
                    $(this).addClass('selected').addClass('bg-primary');
                }
            });

            $(modal_clone).on('click','#btnSave',function(){

                let btn =  $(this);
                $(btn).prop('disable',true);

                const form = $(modal_clone).find('#form_modal_create')[0]; // Obtén el elemento DOM
                let flag_error  = false;
                if (form.checkValidity() === false) {
                    $(form).addClass('was-validated');
                    flag_error  = true;
                } else {
                    $(form).removeClass('was-validated');
                }

                if (flag_error){
                    $(btn).prop('disable',false);
                    return false;
                }

                let obj_info    = [];
                let index       = 0;
                try{
                    $(modal_clone).find('.div_header_hours').each(function(){

                        obj_info[index] = new Object();
                        obj_info[index]['hora_inicio']  = $(this).find('.input_hora_inicio').val();
                        obj_info[index]['hora_termino'] = $(this).find('.input_hora_termino').val();
                        obj_info[index]['dias']         = [];

                        let id_header   = $(this).attr('id');
                        let hora_inicio_header  = convertirHoraATiempo($(this).find('.input_hora_inicio').val());
                        let hora_termino_header = convertirHoraATiempo($(this).find('.input_hora_termino').val());

                        if (hora_termino_header <= hora_inicio_header){
                            throw 'error_minus_ending_date';
                        }
                        //  SE BUSCAN LOS DIAS SELECCIONADOS
                        let tmp_dias    = [];
                        $(this).find('.selected').each(function(){
                            let dia_selected    = $(this).data('dia');
                            tmp_dias.push(dia_selected);

                            //  SE BUSCAN LOS ROWS CUYO DIA SELECCIONADO SEA IGUAL
                            $(modal_clone).find('.rows_table').find('.dia_'+dia_selected).each(function(){
                                console.log('check id');
                                console.log($(this).closest('.div_header_hours').attr('id'));
                                console.log(id_header);
                                if ($(this).closest('.div_header_hours').attr('id') == id_header){
                                    return true;
                                }

                                if (!$(this).hasClass('selected')){
                                    return false;
                                }

                                let hora_inicio     = convertirHoraATiempo($(this).closest('.div_header_hours').find('.input_hora_inicio').val());
                                let hora_termino    = convertirHoraATiempo($(this).closest('.div_header_hours').find('.input_hora_termino').val());

                                //  SE VERIFICA QUE NO EXISTA EMPALADO DE LA HORA INICIAL
                                if (hora_inicio_header >= hora_inicio && hora_inicio_header < hora_termino){
                                    console.log('empalmado hora_inicio_header');
                                    throw 'error_opening_hours';
                                }

                                //  SE VERIFICA EL EMPALMADO CON LA HORA DE TERMINO
                                if (hora_termino_header > hora_inicio && hora_termino_header <= hora_termino){
                                    console.log('empalmado hora termino');
                                    throw 'error_opening_hours';
                                }
                            });

                            
                            obj_info[index]['dias'].push($(this).data('dia'));
                        });

                        if (obj_info[index]['dias'].length == 0){
                            throw 'error_empty_days';
                        }

                        //  SE RECORRE EL DIV DE LOCACIONES, PARA QUE CUMPLA COMO HORARIO ACEPTADO DEBE DE:
                        //  1. tmp_dias DEBE DE ESTAR COMPLETO EN EL DIV DE DIAS DE LOCACION
                        //  2. LAS HORA INICIO Y TERMINO DEBE DE ESTAR DENTRO DEL RANGO DEL DIV
                        let flag_cumplio    = false;
                        $(modal_clone).find('.rows_table_locaciones').find('.div_header_hours_locaciones').each(function(){
                            
                            let hora_inicio_locacion    = convertirHoraATiempo($(this).find('.input_hora_inicio').val());
                            let hora_termino_locacion   = convertirHoraATiempo($(this).find('.input_hora_termino').val());

                            if (hora_inicio_header < hora_inicio_locacion || hora_inicio_header > hora_termino_locacion){
                                console.log('__1');
                                console.log('hora_inicio_header < hora_inicio_locacion',hora_inicio_header < hora_inicio_locacion);
                                console.log('hora_inicio_header > hora_termino_locacion',hora_inicio_header > hora_termino_locacion);
                                return true;
                            } else {
                                if (hora_termino_header < hora_inicio_locacion || hora_termino_header > hora_termino_locacion){
                                    console.log('__2');
                                    return true;
                                }
                            }

                            //  SE VERIFICA EL RANGO DE HORAS QUE CUMPLA
                            let flag_cumplio_dias   = true;
                            for(let i in tmp_dias){
                                if ($(this).find('.dia_'+tmp_dias[i]).hasClass('selected')){
                                    continue;
                                } else {
                                    flag_cumplio_dias   = false;
                                    break;
                                }
                            }

                            if (flag_cumplio_dias){
                                flag_cumplio    = true;
                                return false;
                            }
                        });

                        if (!flag_cumplio){
                            throw   'error_range_allowed';
                        }

                        index ++;
                    });

                }catch(err){
                    console.log('err');
                    console.log(err);
                    let msg_error   = error_list[err];
                    if (err == 'error_empty_days' || err == 'error_range_allowed') console.log('aqui'); msg_error += ' registro: '+(index + 1);
                    $(modal_clone).find('#alert_error').find('#msg_error').html(msg_error);
                    $(modal_clone).find('#alert_error').addClass('d-flex').show();
                    return false;
                }

                $(modal_clone).find('#alert_error').removeClass('d-flex').hide();

                console.log('obj_info');
                console.log(obj_info);

                $.ajax({
                    url     : url_update,
                    method  : 'post',
                    data    : {
                        accion      : 'save_opening_hours',
                        obj_info    : obj_info,
                        id_locacion : $(modal_clone).find('#select_locaciones').val(),
                        locacion        :$(modal_clone).find('#select_locaciones').find('option:selected').text(),
                        id_profesional  : id_profesional,
                        clave           : clave,
                        nombre          : nombre
                    },
                    success     : function(data){
                        $(btn).prop('disabled',false);
                        $(modal_clone).modal('hide');
                        showAlert('success',data);
                    },
                    error     : function(error){
                        actionJsonError(error,btn);
                    }
                })

            });

            $(modal_clone).modal('show');

        }

        function show_modal_horario_fijo(info_citas,btn_inicial){
            let modal_clone = $("#modal_horario_fjo").clone().removeAttr('id').show();

            let rows    = '';

            for(let cita of info_citas){
                rows += 
                        '<tr class="tr_header" data-idcitaprogramada="'+cita.id_cita_programada+'" data-idservicio="'+cita.id_servicio+'">'+
                            '<td class="td_row">'+cita.label_dia+'</td>'+
                            '<td class="td_row">'+cita.hora_inicio+' - '+cita.hora_termino+'</td>'+
                            '<td class="td_row">'+cita.nombre_paciente+'</td>'+
                            '<td class="td_row" align="center" style="background: '+cita.codigo_color+';width: 80px; max-width: 80px; font-size: 0.85rem;">'+cita.clave_servicio+'</td>'+
                            '<td align="center">'+
                                '<div class="btn-group" role="group" aria-label="Acciones de cita">'+
                                    '<button type="button" class="btn btn_editar" data-idpaciente="'+cita.id_paciente+'" title="Editar" ><i class="bi bi-pencil-fill"></i></button>'+
                                    '<button type="button" class="btn btn_transferir" title="Trasferir" data-idservicio="'+cita.id_servicio+'" data-idlocacion="'+cita.id_locacion+'" data-idprofesional="'+cita.id_profesional+'" data-nombrepaciente="'+cita.nombre_paciente+'" data-servicio="'+cita.clave_servicio+'" data-labeldia="'+cita.label_dia+'" data-horario="'+cita.hora_inicio+' - '+cita.hora_termino+'"  data-idcitaprogramadaserviciohorario="'+cita.id_cita_programada_servicio_horario+'" data-nombrelocacion="'+cita.nombre_locacion+'" data-nombreprofesional="'+cita.nombre_profesional+'"><i class="bi bi-arrow-left-right"></i></button>'+
                                    '<button type="button" class="btn btn_borrar" data-nombrepaciente="'+cita.nombre_paciente+'" data-servicio="'+cita.clave_servicio+'" data-labeldia="'+cita.label_dia+'" data-horario="'+cita.hora_inicio+' - '+cita.hora_termino+'"  data-idcitaprogramadaserviciohorario="'+cita.id_cita_programada_servicio_horario+'" title="Elimitar">'+
                                        '<i class="bi bi-trash3-fill"></i>'+
                                    '</button>'+
                            '</div>'+
                            '</td>'+
                        '</tr>';
            }

            if (rows == ''){
                rows    = '<tr><td colspan="5" align="center">'+translations['emptyTable']+'</td></tr>';
            }

            $(modal_clone).find('.table_citas').find('tbody').append(rows);

            //  EVENTOS
            $(modal_clone).on('click','.btn_editar',function(){
                const id_paciente   = $(this).data('idpaciente');
                window.location.href = '/Pacientes/scheduleappointments?id='+id_paciente;
            });

            $(modal_clone).on('click','.btn_borrar', async function(){
                const id_cita_programada_servicio_horario   = $(this).data('idcitaprogramadaserviciohorario');
                const nombre_paciente   = $(this).data('nombrepaciente');
                const servicio          = $(this).data('servicio');
                const horario           = $(this).data('horario');
                const dia               = $(this).data('labeldia');
                const respuesta = await window.modalConfirm(translations['confirm_delete']);
                let btn         = $(this);

                $(btn).prop('disabled',true);

                console.log('id_cita_programada_servicio_horario',id_cita_programada_servicio_horario);
                console.log('nombre_paciente',nombre_paciente);
                console.log('servicio',servicio);
                console.log('horario',horario);

                if (respuesta) {
                    $.ajax({
                        url     : url_update,
                        method  : 'POST',
                        data    : {
                            accion          : 'delete_horario_fijo',
                            nombre_paciente : nombre_paciente,
                            servicio        : servicio,
                            horario         : horario,
                            dia             : dia,
                            id_cita_programada_servicio_horario : id_cita_programada_servicio_horario ,
                        },
                        success : function(data){
                            console.log('data');
                            console.log(data);
                            $(btn).prop('disabled',false);
                            showAlert('success',"Borrado exitosa!");
                            $(modal_clone).modal('hide');
                        },
                        error   : function(error){
                            actionJsonError(error,btn);
                        }
                    });
                } else {
                    $(btn).prop('disabled',false);
                }
            });

            $(modal_clone).on('click','.btn_transferir',function(){
                const id_servicio       = $(this).data('idservicio');
                const id_locacion       = $(this).data('idlocacion');
                const id_profesional    = $(this).data('idprofesional');

                const id_cita_programada_servicio_horario = $(this).data('idcitaprogramadaserviciohorario');
                const nombre_paciente = $(this).data('nombrepaciente');
                const servicio = $(this).data('servicio');
                const horario = $(this).data('horario');
                const dia = $(this).data('labeldia');
                const nombre_locacion       = $(this).data('nombrelocacion');
                const nombre_profesional    = $(this).data('nombreprofesional');

                let info_cita = {
                    id_cita_programada_servicio_horario: id_cita_programada_servicio_horario,
                    nombre_paciente: nombre_paciente,
                    servicio: servicio,
                    horario: horario,
                    dia: dia,
                    nombre_locacion : nombre_locacion,
                    nombre_profesional : nombre_profesional
                };

                $.ajax({
                    url     : url_update,
                    method  : 'POST',
                    data    : {
                        accion          : 'get_profesionales_disponibles',
                        id_servicio     : id_servicio,
                        id_locacion     : id_locacion,
                        id_profesional  : id_profesional
                    },
                    success : function(data){
                        $(modal_clone).modal('hide');
                        show_modal_transferir(info_cita,data,btn_inicial);
                    },
                    error   : function(error){
                        actionJsonError(error,btn);
                    }
                });
            });

            $(modal_clone).modal('show');
        }

        //  MODAL CON TODA LA INFORMACION PARA TRANSFERIR 
        function show_modal_transferir(info_cita,profesionales,btn_inicial){
            console.log('info_cita',info_cita);
            let modal_clone         = $("#modal_transferir").clone().removeAttr('id').show();
            let permitir_guardar    = false;

            $(modal_clone).find('#locacion').text(info_cita['nombre_locacion']);
            $(modal_clone).find('#nombre_paciente').text(info_cita['nombre_paciente']);
            $(modal_clone).find('#servicio').text(info_cita['servicio']);
            $(modal_clone).find('#horario').text(info_cita['dia']+ ' ' +info_cita['horario']);
            $(modal_clone).find('#profesional_actual').text(info_cita['nombre_profesional']);

            let options = '<option value="">Seleccione un profesional</option>';
            for(let row of profesionales){
                options += '<option value="'+row['id']+'">'+row['nombre_completo']+'</option>';
            }

            $(modal_clone).find("#select_profesionales").append(options);

            $(modal_clone).on('change','#select_profesionales',function(){
                if ($(this).val() == null || $(this).val() == ''){
                    return false;
                }

                const id_profesional    = $(this).val();

                $.ajax({
                    url     : url_update,
                    method  : 'POST',
                    data    : {
                        accion          : 'verificar_disponibilidad',
                        id_profesional  : id_profesional,
                        id_cita_programada_servicio_horario : info_cita['id_cita_programada_servicio_horario']
                    },
                    success : function(data){
                        $(modal_clone).find('#alert_error').removeClass('alert-danger').addClass('alert-success');
                        $(modal_clone).find('#alert_error').find('#msg_error').html('Profesional disponible');
                        $(modal_clone).find('#alert_error').addClass('d-flex').show();
                        permitir_guardar    = true;
                    },
                    error   : function(error){
                        $(modal_clone).find('#alert_error').removeClass('alert-success').addClass('alert-danger');
                        $(modal_clone).find('#alert_error').find('#msg_error').html(error.responseText);
                        $(modal_clone).find('#alert_error').addClass('d-flex').show();
                        permitir_guardar    = false;
                        //actionJsonError(error,btn);
                    }
                });                
            });

            $(modal_clone).on('click','#btnSave',function(){

                let btn = $(this);
                $(btn).prop('disabled',true);

                if ($(modal_clone).find("#select_profesionales").val() == null || $(modal_clone).find("#select_profesionales").val() == ''){
                    showAlert('danger','Seleccione un profesional');
                    $(btn).prop('disabled',false);
                    return false;
                }

                if (!permitir_guardar){
                    showAlert('danger','Profesional no disponible');
                    $(btn).prop('disabled',false);
                    return false;
                }

                const id_profesional        = $(modal_clone).find("#select_profesionales").val();
                const nombre_profesional    = $(modal_clone).find("#select_profesionales").find('option:selected').text();

                $.ajax({
                    url         : url_update,
                    method      : 'post',
                    dataType    : 'json',
                    data        : {
                        accion  : 'update_horario_fijo',
                        id_profesional  : id_profesional,
                        nombre_profesional  : nombre_profesional,
                        nombre_paciente     : info_cita['nombre_paciente'],
                        horario             : info_cita['dia']+ ' ' +info_cita['horario'],
                        id_cita_programada_servicio_horario : info_cita['id_cita_programada_servicio_horario']
                    },
                    success     : function(data){
                        showAlert('success','Reasignación exitosa');
                        $(modal_clone).modal('hide');
                    },
                    error   : function(error){
                        actionJsonError(error,btn);
                    }
                });
            });

            $(modal_clone).on('hidden.bs.modal', function (e) {
                $(btn_inicial).trigger('click');
            });

            $(modal_clone).modal('show');
        }
    })();
</script>