<style>
    
/* Estilos específicos para create.phtml */
    .create-container main {
        display: block;
        height: auto;
        overflow: visible;
    }

    .nav-link {
        cursor: pointer;
    }

    .list-group-item {
        border: none;
        cursor: pointer;
    }

    .form-check-input{
        cursor: pointer;
    }

    .hide {
        display: none;
    }

</style>
<div class="create-container container">
    <div class="container-fluid"> <!-- Cambiado de container a container-fluid -->
        <main>
            <div class="row">
                <div class="col-12">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link a_datos_generales active" aria-current="page">Datos generales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link a_perfil">Perfil</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-12 p-3">
                    <div class="datos_generales">
                        <h4 class="mb-3"><?php echo $translations['html_general_data']; ?></h4>
                        <div class="alert alert-success align-items-center alert_cuenta_creada" role="alert" style="display:none;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                            </svg>
                            <div id="msg_error">
                            <?php echo $translations['html_acount_already_exists']; ?>
                            </div>
                        </div>
                        <form id="form_datos_generales" class="needs-validation" novalidate>
                            <div class="row g-3">
                                <div class="col-sm-4">
                                    <label for="input_primer_apellido" class="form-label"><?php echo $translations['html_first_lastname']; ?></label>
                                    <input type="text" class="form-control" id="input_primer_apellido" placeholder="" value="<?php echo $arr_info_profesional['primer_apellido']; ?>" required disabled>
                                    <div class="invalid-feedback">
                                    <?php echo $translations['html_error_first_lastname']; ?>
                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <label for="input_segundo_apellido" class="form-label"><?php echo $translations['html_second_lastname']; ?></label>
                                    <input type="text" class="form-control" id="input_segundo_apellido" placeholder="" value="<?php echo $arr_info_profesional['segundo_apellido']; ?>" disabled>
                                </div>

                                <div class="col-sm-4">
                                    <label for="input_nombre" class="form-label"><?php echo $translations['html_name']; ?></label>
                                    <input type="text" class="form-control" id="input_nombre" placeholder="" value="<?php echo $arr_info_profesional['nombre']; ?>" required disabled>
                                    <div class="invalid-feedback">
                                    <?php echo $translations['html_error_name']; ?>
                                    </div>
                                </div>

                                <div class="col-6">
                                    <label for="input_celular" class="form-label"><?php echo $translations['html_cellphone']; ?></label>
                                    <input type="text" class="form-control" id="input_celular" placeholder="" value="<?php echo $arr_info_profesional['celular']; ?>" required disabled>
                                    <div class="invalid-feedback">
                                    <?php echo $translations['html_error_cellphone']; ?>
                                    </div>
                                </div>

                                <div class="col-6">
                                    <label for="input_correo_electronico" class="form-label"><?php echo $translations['html_email']; ?></label>
                                    <input type="email" class="form-control" id="input_correo_electronico" placeholder="you@example.com" value="<?php echo $arr_info_profesional['correo_electronico']; ?>" disabled>
                                </div>

                                <div class="col-12">
                                    <label for="input_direccion" class="form-label"><?php echo $translations['html_address']; ?></label>
                                    <input type="text" class="form-control" id="input_direccion" placeholder="Calle 1 #12 Col: Olvares" value="<?php echo $arr_info_profesional['direccion']; ?>" disabled disabled>
                                    <div class="invalid-feedback">
                                        Please enter your shipping address.
                                    </div>
                                </div>

                                <div class="col-4">
                                    <label for="input_titulo_profesional" class="form-label"><?php echo $translations['html_professional_title']; ?></label>
                                    <input type="text" class="form-control" id="input_titulo_profesional" placeholder="Mtro" required value="<?php echo $arr_info_profesional['titulo']; ?>" disabled>
                                </div>

                                <div class="col-4">
                                    <label for="input_cedula_profesional" class="form-label"><?php echo $translations['html_professional_id']; ?></label>
                                    <input type="text" class="form-control" id="input_cedula_profesional" placeholder="12345678" value="<?php echo $arr_info_profesional['cedula_profesional']; ?>" disabled>
                                </div>
                            </div>
                            <div id="alert_error_datos_generales" class="alert alert-danger align-items-center" role="alert" style="display:none;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg>
                                <div id="msg_error">
                                    
                                </div>
                            </div>
                            <hr class="my-4">
                            <div class="col-12" align="right">
                                <button type="button" class="btn btn-outline-dark btnReturn" ><?php echo $translations['html_btn_return']; ?></button>
                            </div>
                        </form>
                    </div>
                    <div class="datos_perfil" style="display:none;">
                        <h4 class="mb-3"><?php echo $translations['html_profile']; ?></h4>
                        <div class="alert alert-success align-items-center alert_cuenta_creada" role="alert" style="display:none;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                            </svg>
                            <div id="msg_error">
                            <?php echo $translations['html_acount_already_exists']; ?>
                            </div>
                        </div>
                        <form id="form_datos_perfil" class="needs-validation" novalidate>
                            <div class="row g-3">
                                <div class="col-4">
                                    <label for="input_perfil_celular" class="form-label"><?php echo $translations['html_access_key']; ?></label>
                                    <input type="text" class="form-control" id="input_perfil_celular" disabled required value="<?php echo $arr_info_profesional['clave']; ?>">
                                    <div class="invalid-feedback">
                                    <?php echo $translations['html_error_cellphone']; ?>
                                    </div>
                                </div>
                                <div class="col-4">
                                    <label for="input_tipo_usuario" class="form-label"><?php echo $translations['html_user_type']; ?></label>
                                    <input type="email" class="form-control" id="input_tipo_usuario" value="<?php echo $arr_tipo_usuario['nombre']; ?>" disabled>
                                </div>
                                <div class="col-12"></div>
                                <div class="container col-12" style="overflow:scroll; height:250px;margin-left: 0;">
                                <!-- LISTA DE SERVICIOS -->
                                    <label class="form-check-label" >
                                    <?php echo $translations['html_locations'].' / '.$translations['html_services']; ?>
                                    </label>
                                    <div class="list-group div_header_locaciones">
                                        <?php foreach($arr_locaciones as $locacion): ?>
                                            <div class="div_header">
                                                <div class="d-flex align-items-center"> <!-- Flex para alinear elementos -->
                                                        <label class="list-group-item parent-option mb-0 me-2"> <!-- Espaciado entre checkbox y texto -->
                                                        <input class="form-check-input me-1 header_check" type="checkbox" value="<?php echo $locacion['id']; ?>" <?php echo isset($arr_info_profesional['locaciones_servicios'][$locacion['id']]) ? 'checked' : ''; ?> disabled>
                                                        </label>
                                                        <span class="span_controlador" style="cursor: pointer;"><?php echo $locacion['nombre']; ?></span> <!-- Texto alineado con el checkbox -->
                                                    </div>
                                                <div class="ms-4 child-options">
                                                    <?php foreach($locacion['servicios'] as $servicio): ?>
                                                        <label class="list-group-item <?php echo !isset($arr_info_profesional['locaciones_servicios'][$locacion['id']]) ? 'hide' : ''; ?> div_label_accion">
                                                            <input class="form-check-input check_sublist" type="checkbox" value="<?php echo $servicio['id_servicio']; ?>" data-idlocacion="<?php echo $locacion['id']; ?>" <?php echo isset($arr_info_profesional['locaciones_servicios'][$locacion['id']][$servicio['id_servicio']]) ? 'checked' : ''; ?> disabled>
                                                            <span class="span_accion"><?php echo $servicio['nombre']; ?></span>
                                                        </label>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>
                            <div id="alert_error_datos_perfil" class="alert alert-danger align-items-center" role="alert" style="display:none;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg>
                                <div id="msg_error">
                                    
                                </div>
                            </div>
                            <hr class="my-4">
                            <div class="col-12" align="right">
                                <button type="button" class="btn btn-outline-dark btnReturn"><?php echo $translations['html_btn_return']; ?></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

<script>
    let module_create_professional  = (function(){

        //  ID A EDITAR
        const id    = "<?php echo $id; ?>";

        //  URL
        const controller    = '/Profesionales';
        const url_index     = controller+"/index";
        const url_update    = controller+"/update";

        //  LISTA DE ERRORES EN MODAL
        const error_list = {
            sin_permisos    : "<?php echo $translations['html_error_empty_list']; ?>",
            error_email     : "<?php echo $translations['html_error_email']; ?>",
            error_celular   : "<?php echo $translations['html_error_cellphone']; ?>",
            error_contrasena    : "<?php echo $translations['html_error_different_password']; ?>",
            error_length_contrasena     : "<?php echo $translations['html_error_length_password']; ?>",
            error_validate_cellphone    : "<?php echo $translations['html_error_validate_cellphone']; ?>",
            error_verify_general_data   : "<?php echo $translations['html_error_verify_general_data']; ?>",
            error_verify_cellphone_user : "<?php echo $translations['html_error_verify_cellphone_user']; ?>",
        }

        const tipo_usuario_defeco   = "<?php echo $arr_tipo_usuario['nombre']; ?>";

        //  BANDERA PARA SABEREL NUMERO QUE YA SE VALIDO
        let celular_validado    = '';

        $(document).ready(function(){
            
            //  EVENTO PARA CAMBIO A PESTAÑA DE PERFIL
            $(".create-container").on('click',".a_perfil",function(){
                console.log('aqui click');
                const form = $('.create-container').find('#form_datos_generales')[0]; // Obtén el elemento DOM
                let flag_error  = false;
                if (form.checkValidity() === false) {
                    $(form).addClass('was-validated');
                    flag_error  = true;
                } else {
                    $(form).removeClass('was-validated');
                }

                if ($('.create-container').find('#input_celular').val() != '' && $('.create-container').find('#input_celular').val().length != 10){
                    $('.create-container').find('#alert_error_datos_generales').find('#msg_error').html(error_list['error_celular']);
                    $('.create-container').find('#alert_error_datos_generales').addClass('d-flex').show();
                    return false;
                }

                if ($('.create-container').find('#input_correo_electronico').val() != '' && !validarEmail($('.create-container').find('#input_correo_electronico').val())){
                    $('.create-container').find('#alert_error_datos_generales').find('#msg_error').html(error_list['error_email']);
                    $('.create-container').find('#alert_error_datos_generales').addClass('d-flex').show();
                    return false;
                }

                console.log('flag_error');
                console.log(flag_error);
                if (!flag_error){

                    $('.create-container').find('#alert_error_datos_generales').find('#msg_error').html('');
                    $('.create-container').find('#alert_error_datos_generales').removeClass('d-flex').hide();

                    console.log('pase');
                    $(".create-container").find('.datos_generales').hide();
                    $(".create-container").find('.datos_perfil').show();

                    $(".create-container").find('.a_datos_generales').removeClass('active');
                    $(".create-container").find('.a_perfil').addClass('active');
                    
                }
            });

            //  EVENTO PARA CAMBIAR A PESTAÑA DE DATOS
            $(".create-container").on('click',".a_datos_generales",function(){
                $(".create-container").find('.datos_generales').show();
                $(".create-container").find('.datos_perfil').hide();

                $(".create-container").find('.a_datos_generales').addClass('active');
                $(".create-container").find('.a_perfil').removeClass('active');
            });

            //  EVENTOS PARA IMPEDIR LETRAS EN IMPUT_CELULAR
            $(".create-container").on('keypress','#input_celular',function(e) {
                if(isNaN(this.value + String.fromCharCode(e.charCode))) 
                return false;
            })
            .on("cut copy paste",function(e){
                e.preventDefault();
            });
            //  EVENTOS MODAL
            $(".create-container").on('click','.span_controlador',function(){
                console.log($(this).closest('.div_header').find('.hide').length);
                if ($(this).closest('.div_header').find('.hide').length > 0){
                    $(this).closest('.div_header').find('.div_label_accion').removeClass('hide');
                } else {
                    $(this).closest('.div_header').find('.div_label_accion').addClass('hide');
                }
            });

            //  EVENTO PARA CHECK
            $(".create-container").on('click','.header_check',function(){
                let status_check    = $(this).prop('checked');
                $(this).closest('.div_header').find('.check_sublist').prop('checked',status_check);
            });

            $(".create-container").on('click','.check_sublist',function(){
                let count_elements  = $(this).closest('.child-options').find('.check_sublist').length;

                if ($(this).closest('.child-options').find('.check_sublist:checked').length > 0){
                    $(this).closest('.div_header').find('.header_check').prop('checked',true);
                }

                if ($(this).closest('.child-options').find('.check_sublist:checked').length == 0){
                    $(this).closest('.div_header').find('.header_check').prop('checked',false);
                }
            });

            //
            $(".create-container").on('click',".btnReturn",function(){
                window.location = "/Profesionales";
            });
        });
    })();
</script>